package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/goobers/goobers/providers"
)

// Capability x provider matrix generation (CONF-2, #2075, design doc §5/§7
// item 2). docs/provider-capability-matrix.md is a committed, build-time-
// generated table sourced from providers.BuildMatrix() — the same
// declarations + gap registry the blessed-tier CI gate
// (providers.TestBlessedTierGapsAreTracked) checks. A drift test regenerates
// and diffs it, the same discipline as the CLI reference (#1096) and the
// feature matrix (#430). `make docs` regenerates it.

// capabilityMatrixFile is the generated doc's path relative to docs/.
const capabilityMatrixFile = "provider-capability-matrix.md"

// renderCapabilityMatrix produces the Markdown capability matrix from
// providers.BuildMatrix().
func renderCapabilityMatrix() string {
	cells := providers.BuildMatrix()
	byCapability := make(map[providers.Capability]map[providers.ProviderKind]providers.MatrixCell, len(cells))
	for _, cell := range cells {
		row, ok := byCapability[cell.Capability]
		if !ok {
			row = make(map[providers.ProviderKind]providers.MatrixCell, len(providers.AllProviderKinds()))
			byCapability[cell.Capability] = row
		}
		row[cell.Provider] = cell
	}

	required := providers.WorkflowRequiredCapabilities()
	support := providers.AllProviderSupport()
	kinds := providers.AllProviderKinds()

	var b strings.Builder
	b.WriteString("# Provider capability matrix\n\n")
	b.WriteString("<!-- Generated by `make docs` from providers.BuildMatrix() (see providers/capability_matrix.go). DO NOT edit by hand. -->\n\n")
	b.WriteString("## Provider support\n\n")
	b.WriteString("Capability conformance records implemented surfaces; it does not override a provider's support designation.\n\n")
	b.WriteString("| Provider | Support | Promotion criteria |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, provider := range support {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", provider.Provider, provider.Level, provider.PromotionCriteria)
	}
	b.WriteString("\n## Capabilities\n\n")
	b.WriteString("Every declared capability (`providers.Capability`, design doc `docs/design/provider-contract-conformance.md` §3.1) ")
	b.WriteString("projected across every registered provider. `required` marks capabilities in `providers.WorkflowRequiredCapabilities()` — ")
	b.WriteString("the set the blessed tier (GitHub, ADO) must be conformant on or have a linked gap issue for; other capabilities are informational.\n\n")
	b.WriteString("| Capability | Required |")
	for _, provider := range support {
		fmt.Fprintf(&b, " %s", provider.Provider)
		if provider.Level == providers.ProviderExperimental {
			b.WriteString(" (experimental)")
		}
		b.WriteString(" |")
	}
	b.WriteString("\n| --- | --- |")
	for range kinds {
		b.WriteString(" --- |")
	}
	b.WriteString("\n")

	for _, cap := range providers.AllCapabilities() {
		req := ""
		if required.Has(cap) {
			req = "yes"
		}
		fmt.Fprintf(&b, "| `%s` | %s |", cap, req)
		for _, kind := range kinds {
			cell := byCapability[cap][kind]
			fmt.Fprintf(&b, " %s |", formatMatrixCell(cell))
		}
		b.WriteString("\n")
	}
	return b.String()
}

// formatMatrixCell renders one cell's status, linking a tracked gap issue
// when present (GitHub auto-links a bare "#NNN" within this repo).
func formatMatrixCell(cell providers.MatrixCell) string {
	if cell.GapIssue == "" {
		return string(cell.Status)
	}
	return fmt.Sprintf("%s (%s)", cell.Status, cell.GapIssue)
}

// writeCapabilityMatrix writes the generated matrix to
// docsDir/provider-capability-matrix.md. Used by `make docs` via the drift
// test's update mode.
func writeCapabilityMatrix(docsDir string) error {
	path := filepath.Join(docsDir, capabilityMatrixFile)
	return os.WriteFile(path, []byte(renderCapabilityMatrix()), 0o644)
}
