package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/goobers/goobers/internal/workflow"
)

// Feature-matrix generation (#430, VER-4). docs/feature-matrix.md is a committed,
// build-time-generated table of every workflow-DSL feature this build supports,
// sourced from the same workflow.AllFeatures() registry the `goobers features`
// command prints. A drift test (featuresdoc_test.go) regenerates and diffs it, so
// the doc can never fall out of sync with the shipped binary — the same
// discipline as the CLI reference (#1096) and the JSON-schema parity checks.
// `make docs` regenerates it.

// featureMatrixFile is the generated doc's path relative to the docs/ directory.
const featureMatrixFile = "feature-matrix.md"

// renderFeatureMatrix produces the Markdown feature matrix. It is pure — it reads
// only workflow.AllFeatures() — so the drift test and the writer share one
// source, exactly as the `goobers features` command does.
func renderFeatureMatrix() string {
	var b strings.Builder
	b.WriteString("# Workflow DSL feature matrix\n\n")
	b.WriteString("<!-- Generated by `make docs` from internal/workflow (see `goobers features`). DO NOT edit by hand. -->\n\n")
	b.WriteString("Every workflow-DSL feature this build of goobers understands, with its ")
	b.WriteString("current support level and the version it entered that level. ")
	b.WriteString("Run `goobers features` to print this table from the running binary, or ")
	b.WriteString("`goobers features --used` to list only the features a given instance references.\n\n")
	b.WriteString("| Feature | Support | Since |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, feature := range workflow.AllFeatures() {
		fmt.Fprintf(&b, "| `%s` | %s | %s |\n", feature.ID, feature.Level, feature.SinceVersion)
	}
	return b.String()
}

// writeFeatureMatrix writes the generated matrix to docsDir/feature-matrix.md.
// Used by `make docs` via the drift test's update mode.
func writeFeatureMatrix(docsDir string) error {
	path := filepath.Join(docsDir, featureMatrixFile)
	return os.WriteFile(path, []byte(renderFeatureMatrix()), 0o644)
}
