package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/goobers/goobers/internal/supportmatrix"
	"github.com/goobers/goobers/internal/workflow"
)

// Feature-matrix generation (#430, VER-4). docs/feature-matrix.md is a committed,
// build-time-generated table of every workflow-DSL feature this build supports,
// sourced from the same feature registry and DSL SupportMatrix the
// `goobers features` command prints. A drift test regenerates and diffs it, so
// the doc can never fall out of sync with the shipped binary — the same
// discipline as the CLI reference (#1096) and the JSON-schema parity checks.
// `make docs` regenerates it.

// featureMatrixFile is the generated doc's path relative to the docs/ directory.
const featureMatrixFile = "feature-matrix.md"

// renderFeatureMatrix produces the Markdown feature matrix from the same
// registry and SupportMatrix used by `goobers features`.
func renderFeatureMatrix() (string, error) {
	features := workflow.AllFeatures()
	rows, err := featureMatrixRows(features, "")
	if err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Workflow DSL feature matrix\n\n")
	b.WriteString("<!-- Generated by `make docs` from the feature registry and DSL SupportMatrix (see `goobers features`). DO NOT edit by hand. -->\n\n")
	b.WriteString("Every workflow-DSL feature this build of goobers understands, projected across ")
	b.WriteString("the DSL versions declared by this binary. ")
	b.WriteString("Run `goobers features` to print this table from the running binary, or ")
	b.WriteString("`goobers features --dsl-version <version>` to scope it to one DSL version.\n\n")
	b.WriteString("| Feature | DSL version | Feature support | Version support | Since app version |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, row := range rows {
		fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n",
			row.Feature.ID,
			row.DSLVersion,
			row.Feature.Level,
			row.DSLLevel,
			row.Feature.SinceVersion,
		)
	}

	b.WriteString("\n## Adjacent-version deltas\n\n")
	versions := supportmatrix.GetDSL().Versions()
	if len(versions) < 2 {
		b.WriteString("No adjacent DSL versions are declared yet.\n")
		return b.String(), nil
	}
	for i := 1; i < len(versions); i++ {
		from, to := versions[i-1].Version, versions[i].Version
		delta, err := featureVersionDelta(features, from, to)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "### %s -> %s\n\n", from, to)
		fmt.Fprintf(&b, "- Added: %s\n", markdownFeatureList(delta.Added))
		fmt.Fprintf(&b, "- Removed: %s\n", markdownFeatureList(delta.Removed))
		fmt.Fprintf(&b, "- Level changes: %s\n\n", markdownFeatureList(delta.LevelChanges))
	}
	return b.String(), nil
}

// writeFeatureMatrix writes the generated matrix to docsDir/feature-matrix.md.
// Used by `make docs` via the drift test's update mode.
func writeFeatureMatrix(docsDir string) error {
	path := filepath.Join(docsDir, featureMatrixFile)
	rendered, err := renderFeatureMatrix()
	if err != nil {
		return err
	}
	return os.WriteFile(path, []byte(rendered), 0o644)
}

type featureDelta struct {
	Added        []string
	Removed      []string
	LevelChanges []string
}

func featureVersionDelta(features []workflow.Feature, from, to string) (featureDelta, error) {
	fromFeatures, err := workflow.FeaturesAtDSLVersion(features, from)
	if err != nil {
		return featureDelta{}, err
	}
	toFeatures, err := workflow.FeaturesAtDSLVersion(features, to)
	if err != nil {
		return featureDelta{}, err
	}
	fromByID := make(map[workflow.FeatureID]workflow.Feature, len(fromFeatures))
	toByID := make(map[workflow.FeatureID]workflow.Feature, len(toFeatures))
	for _, feature := range fromFeatures {
		fromByID[feature.ID] = feature
	}
	for _, feature := range toFeatures {
		toByID[feature.ID] = feature
	}

	var delta featureDelta
	for _, feature := range toFeatures {
		previous, ok := fromByID[feature.ID]
		if !ok {
			delta.Added = append(delta.Added, string(feature.ID))
			continue
		}
		if previous.Level != feature.Level {
			delta.LevelChanges = append(delta.LevelChanges,
				fmt.Sprintf("%s (%s -> %s)", feature.ID, previous.Level, feature.Level))
		}
	}
	for _, feature := range fromFeatures {
		if _, ok := toByID[feature.ID]; !ok {
			delta.Removed = append(delta.Removed, string(feature.ID))
		}
	}
	return delta, nil
}

func markdownFeatureList(features []string) string {
	if len(features) == 0 {
		return "none"
	}
	quoted := make([]string, len(features))
	for i, feature := range features {
		quoted[i] = "`" + feature + "`"
	}
	return strings.Join(quoted, ", ")
}
