package telemetry

import (
	"log/slog"
	"sync"
	"time"

	"go.opentelemetry.io/otel"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// exportErrorRepeatWindow bounds how often one recurring export failure may be
// logged. The OTLP periodic reader retries on its own interval — 60s on this
// deployment — so an unrecoverable condition otherwise produces a line every
// minute, forever, in the same log an operator greps for real faults.
const exportErrorRepeatWindow = 30 * time.Minute

// exportErrorDistinctLimit bounds the signature table. Export errors are
// generated by machines and repeat verbatim, so the table stays tiny in
// practice; the cap exists so that an error carrying a varying detail (a port,
// a deadline) cannot grow it without bound in a long-lived daemon.
const exportErrorDistinctLimit = 64

// exportErrorHandler is the global OpenTelemetry error handler. The SDK's
// default writes every asynchronous export failure straight to the standard
// logger, which is correct for a short-lived process and wrong for a daemon:
// see #4159. This one keeps the first occurrence of each distinct failure —
// the operator still learns immediately that export is broken — then reports a
// recurrence at most once per window, with the count it stands for.
//
// It also names the one condition retrying cannot fix. A collector that answers
// gRPC Unimplemented has accepted the connection and refused the signal, which
// is a configuration statement, not a transient fault.
type exportErrorHandler struct {
	mu     sync.Mutex
	seen   map[string]*exportErrorRecord
	window time.Duration
	now    func() time.Time
	log    func(msg string, args ...any)
}

type exportErrorRecord struct {
	suppressed int
	lastEmit   time.Time
}

func newExportErrorHandler() *exportErrorHandler {
	return &exportErrorHandler{
		seen:   make(map[string]*exportErrorRecord),
		window: exportErrorRepeatWindow,
		now:    time.Now,
		log: func(msg string, args ...any) {
			slog.Warn(msg, args...)
		},
	}
}

// Handle implements otel.ErrorHandler.
func (h *exportErrorHandler) Handle(err error) {
	if err == nil {
		return
	}
	msg, args, ok := h.classify(err)
	if !ok {
		return
	}
	h.log(msg, args...)
}

// classify records the occurrence and reports whether it should be logged now.
func (h *exportErrorHandler) classify(err error) (string, []any, bool) {
	key := err.Error()
	now := h.now()

	h.mu.Lock()
	defer h.mu.Unlock()

	record, seen := h.seen[key]
	if !seen {
		// Reset rather than evict-one: which signature is oldest carries no
		// meaning here, and a reset re-announces every live condition once,
		// which is the safe direction for an operator-facing log.
		if len(h.seen) >= exportErrorDistinctLimit {
			h.seen = make(map[string]*exportErrorRecord)
		}
		h.seen[key] = &exportErrorRecord{lastEmit: now}
		return "telemetry export failed", appendHint([]any{"error", key}, err), true
	}

	record.suppressed++
	if now.Sub(record.lastEmit) < h.window {
		return "", nil, false
	}
	args := []any{"error", key, "repeats", record.suppressed, "window", h.window.String()}
	record.suppressed = 0
	record.lastEmit = now
	return "telemetry export still failing", appendHint(args, err), true
}

func appendHint(args []any, err error) []any {
	if hint := exportErrorHint(err); hint != "" {
		return append(args, "hint", hint)
	}
	return args
}

// exportErrorHint explains a failure whose cause is not what the raw message
// suggests. Unimplemented is the one that matters on this deployment: the
// collector is up and reachable, and has simply not been given a pipeline for
// the signal, so no amount of retrying changes the answer.
func exportErrorHint(err error) string {
	if status.Code(err) == codes.Unimplemented {
		return "the collector is reachable but serves no pipeline for this signal; " +
			"add the pipeline to the collector or disable the signal — retrying cannot succeed"
	}
	return ""
}

var installExportErrorHandlerOnce sync.Once

// installExportErrorHandler replaces the SDK's default global error handler.
// It runs once per process: the handler is global state, and a second install
// would discard the first's suppression table and restart the log storm.
func installExportErrorHandler() {
	installExportErrorHandlerOnce.Do(func() {
		otel.SetErrorHandler(newExportErrorHandler())
	})
}
