// Code generated by go generate ./internal/apicontract; DO NOT EDIT.

export const apiRoutes = {
  "health": { method: "GET", path: "/api/v1/health" },
  "instance": { method: "GET", path: "/api/v1/instance" },
  "gaggles": { method: "GET", path: "/api/v1/gaggles" },
  "gaggleGoobers": { method: "GET", path: "/api/v1/gaggles/{gaggle}/goobers" },
  "gaggleWorkflows": { method: "GET", path: "/api/v1/gaggles/{gaggle}/workflows" },
  "workflowDetail": { method: "GET", path: "/api/v1/gaggles/{gaggle}/workflows/{workflow}" },
  "runs": { method: "GET", path: "/api/v1/runs" },
  "runDetail": { method: "GET", path: "/api/v1/runs/{run}" },
  "runEvents": { method: "GET", path: "/api/v1/runs/{run}/events" },
  "stageAttempts": { method: "GET", path: "/api/v1/runs/{run}/stages/{stage}/attempts" },
  "runArtifact": { method: "GET", path: "/api/v1/runs/{run}/artifacts/{digest}" },
  "telemetryStats": { method: "GET", path: "/api/v1/telemetry/stats" },
  "telemetryErrors": { method: "GET", path: "/api/v1/telemetry/errors" },
  "events": { method: "GET", path: "/api/v1/events" },
} as const;

export type ApiRoute = (typeof apiRoutes)[keyof typeof apiRoutes];

export const runtimeMutationCapabilities = [] as const;

export type RuntimeMutationCapabilityId =
  (typeof runtimeMutationCapabilities)[number];
