// Code generated by go generate ./internal/apicontract; DO NOT EDIT.

export const apiRoutes = {
  "health": { method: "GET", path: "/api/v1/health", actionClass: "read-only-navigation" },
  "instance": { method: "GET", path: "/api/v1/instance", actionClass: "read-only-navigation" },
  "portalConfig": { method: "GET", path: "/api/v1/portal/config", actionClass: "read-only-navigation" },
  "gaggles": { method: "GET", path: "/api/v1/gaggles", actionClass: "read-only-navigation" },
  "gaggleGoobers": { method: "GET", path: "/api/v1/gaggles/{gaggle}/goobers", actionClass: "read-only-navigation" },
  "gaggleWorkflows": { method: "GET", path: "/api/v1/gaggles/{gaggle}/workflows", actionClass: "read-only-navigation" },
  "workflowDetail": { method: "GET", path: "/api/v1/gaggles/{gaggle}/workflows/{workflow}", actionClass: "read-only-navigation" },
  "runs": { method: "GET", path: "/api/v1/runs", actionClass: "read-only-navigation" },
  "runDetail": { method: "GET", path: "/api/v1/runs/{run}", actionClass: "read-only-navigation" },
  "runEvents": { method: "GET", path: "/api/v1/runs/{run}/events", actionClass: "read-only-navigation" },
  "stageAttempts": { method: "GET", path: "/api/v1/runs/{run}/stages/{stage}/attempts", actionClass: "read-only-navigation" },
  "runArtifact": { method: "GET", path: "/api/v1/runs/{run}/artifacts/{digest}", actionClass: "read-only-navigation" },
  "telemetryStats": { method: "GET", path: "/api/v1/telemetry/stats", actionClass: "read-only-navigation" },
  "telemetryErrorSignatures": { method: "GET", path: "/api/v1/telemetry/error-signatures", actionClass: "read-only-navigation" },
  "telemetryErrors": { method: "GET", path: "/api/v1/telemetry/errors", actionClass: "read-only-navigation" },
  "events": { method: "GET", path: "/api/v1/events", actionClass: "read-only-navigation" },
} as const;

export type ApiRoute = (typeof apiRoutes)[keyof typeof apiRoutes];

export const runtimeMutationCapabilities = [] as const;

export type RuntimeMutationCapabilityId =
  (typeof runtimeMutationCapabilities)[number];

export const actionClasses = {
  runtimeMutation: "runtime-mutation",
  readOnlyNavigation: "read-only-navigation",
  configTime: "config-time",
  daemonLifecycle: "daemon-lifecycle",
  workflowExecution: "workflow-execution",
  maintenance: "maintenance",
} as const;

export type ActionClass =
  (typeof actionClasses)[keyof typeof actionClasses];

export type SurfaceAction =
  | { id: string; class: typeof actionClasses.runtimeMutation; capability: RuntimeMutationCapabilityId }
  | { id: string; class: Exclude<ActionClass, typeof actionClasses.runtimeMutation>; capability?: never };
