// Code generated by go generate ./internal/apicontract; DO NOT EDIT.

import type {
  GaggleEventEnvelope,
  GaggleEventReceipt,
  MetadataChangeRequest,
  MetadataObjectiveRequest,
  MetadataAliasRequest,
  MetadataPreview,
  MetadataProposalCommand,
  WorkbenchDocumentPage,
  WorkbenchGraph,
  BacklogWriteCapabilities,
  BacklogPatchInput,
  BacklogEditCommand,
  WorkbenchSourcePage,
  BacklogPage,
  BacklogItem,
  SessionCreateRequest,
  SessionMessageRequest,
  SessionCloseRequest,
  InteractiveSession,
  SessionPage,
  SessionMessagePage,
  SessionAcceptance,
  ChildPublicationCheckRequest,
  ChildPublicationCheckResult,
  ChildWorkflowPage,
  InteractiveRunView,
  InteractiveRunCommand,
  InteractiveRunCommandResult,
  InteractiveCapabilities,
  ChildWorkflowSourceRequest,
  ChildWorkflowStatusRequest,
  ChildWorkflowResolveRequest,
  ChildWorkflowResolutionResponse,
  ChildWorkflowValidationResponse,
  ChildWorkflowResponse,
  TriggerRequest,
  TriggerResponse,
  TriggerStatusResponse,
  CancelRunRequest,
  CancelRunResult,
  OperatorMessageSubmitRequest,
  OperatorMessageSubmitResponse,
  QueueEligibilityView,
  Health,
  Instance,
  PortalConfig,
  GagglePage,
  GooberPage,
  WorkflowPage,
  WorkflowDetail,
  RunList,
  RunDetail,
  EventList,
  AttemptList,
  TelemetryCostResult,
  TelemetryStatsResult,
  TelemetryErrorSignaturesResult,
  TelemetryErrorsPage,
  ConfigSourcePage,
  ConfigDocumentPage,
  ConfigDocumentRequest,
  ConfigDocument,
  ConfigChangePreviewRequest,
  ConfigChangePreview,
  ConfigWriteRequest,
  ConfigWriteOutcome,
  ConfigAuthoringErrorEnvelope,
  ModelInvalidation,
  ApiErrorEnvelope,
} from "./types";

export interface GoWireFixtures {
  gaggleEventEnvelope: GaggleEventEnvelope;
  gaggleEventReceipt: GaggleEventReceipt;
  metadataChange: MetadataChangeRequest;
  metadataObjective: MetadataObjectiveRequest;
  metadataAlias: MetadataAliasRequest;
  metadataPreview: MetadataPreview;
  metadataProposal: MetadataProposalCommand;
  workbenchDocuments: WorkbenchDocumentPage;
  workbenchGraph: WorkbenchGraph;
  workbenchWriteCapabilities: BacklogWriteCapabilities;
  workbenchPatch: BacklogPatchInput;
  workbenchCommand: BacklogEditCommand;
  workbenchSources: WorkbenchSourcePage;
  workbenchItems: BacklogPage;
  workbenchItem: BacklogItem;
  sessionCreate: SessionCreateRequest;
  sessionInput: SessionMessageRequest;
  sessionClose: SessionCloseRequest;
  session: InteractiveSession;
  sessions: SessionPage;
  sessionMessages: SessionMessagePage;
  sessionAccepted: SessionAcceptance;
  childPublicationCheck: ChildPublicationCheckRequest;
  childPublicationResult: ChildPublicationCheckResult;
  childWorkflowPage: ChildWorkflowPage;
  interactiveRun: InteractiveRunView;
  interactiveRunCommand: InteractiveRunCommand;
  interactiveRunResult: InteractiveRunCommandResult;
  interactiveCapabilities: InteractiveCapabilities;
  childWorkflowSource: ChildWorkflowSourceRequest;
  childWorkflowStatus: ChildWorkflowStatusRequest;
  childWorkflowResolve: ChildWorkflowResolveRequest;
  childWorkflowResolution: ChildWorkflowResolutionResponse;
  childWorkflowValidation: ChildWorkflowValidationResponse;
  childWorkflow: ChildWorkflowResponse;
  triggerRequest: TriggerRequest;
  triggerResponse: TriggerResponse;
  triggerStatus: TriggerStatusResponse;
  cancelRequest: CancelRunRequest;
  cancelResult: CancelRunResult;
  operatorMessageRequest: OperatorMessageSubmitRequest;
  operatorMessageResponse: OperatorMessageSubmitResponse;
  queueEligibility: QueueEligibilityView;
  health: Health;
  instance: Instance;
  portalConfig: PortalConfig;
  gaggles: GagglePage;
  goobers: GooberPage;
  workflows: WorkflowPage;
  workflowDetail: WorkflowDetail;
  runs: RunList;
  runDetail: RunDetail;
  runEvents: EventList;
  stageAttempts: AttemptList;
  telemetryCosts: TelemetryCostResult;
  telemetryStats: TelemetryStatsResult;
  telemetryErrorSignatures: TelemetryErrorSignaturesResult;
  telemetryErrors: TelemetryErrorsPage;
  configSources: ConfigSourcePage;
  configDocuments: ConfigDocumentPage;
  configDocumentRequest: ConfigDocumentRequest;
  configDocument: ConfigDocument;
  configPreviewRequest: ConfigChangePreviewRequest;
  configPreview: ConfigChangePreview;
  configWriteRequest: ConfigWriteRequest;
  configWriteOutcome: ConfigWriteOutcome;
  configAuthoringError: ConfigAuthoringErrorEnvelope;
  eventInvalidation: ModelInvalidation;
  errorEnvelope: ApiErrorEnvelope;
}

export const goWireFixtures = {
  "gaggleEventEnvelope": {
    "specversion": "1.0",
    "id": "change-1",
    "source": "urn:factory:builds",
    "type": "build.finished",
    "data": {
      "result": "passed"
    }
  },
  "gaggleEventReceipt": {
    "receiptId": "event-0123456789abcdef0123456789abcdef",
    "gaggle": "web",
    "binding": "ingress:builds",
    "source": "urn:factory:builds",
    "eventId": "change-1",
    "digest": "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
    "acceptedAt": "2026-10-04T12:00:00Z",
    "duplicate": false,
    "state": "routing_pending",
    "statusUrl": "/api/v1/gaggles/web/events/event-0123456789abcdef0123456789abcdef",
    "tombstoned": false,
    "deliveries": []
  },
  "metadataChange": {
    "path": "plan.md",
    "expected": {
      "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "blobId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      "contentDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    },
    "field": "description",
    "value": "# Revised strategy\n"
  },
  "metadataObjective": {
    "path": "plan.md",
    "expected": {
      "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "blobId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      "contentDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    },
    "objective": {
      "objectiveId": "obj-00000000-0000-0000-0000-000000000001",
      "title": "Assigned objective"
    }
  },
  "metadataAlias": {
    "path": "relationships.yaml",
    "expected": {
      "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "blobId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      "contentDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    },
    "alias": {
      "action": "add",
      "alias": {
        "name": "delivery",
        "target": {
          "gaggleId": "web",
          "sourceBindingId": "strategy",
          "kind": "objective-document",
          "sourceId": "obj-00000000-0000-0000-0000-000000000001"
        }
      }
    }
  },
  "metadataPreview": {
    "path": "plan.md",
    "expected": {
      "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "blobId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      "contentDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    },
    "targetDigest": "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    "operationDigest": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    "proposedContentDigest": "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
    "changed": true,
    "before": "# Strategy\n",
    "after": "# Revised strategy\n"
  },
  "metadataProposal": {
    "id": "workbench-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "gaggle": "web",
    "sourceBindingId": "strategy",
    "actor": {
      "issuer": "https://identity.example",
      "subject": "alice"
    },
    "path": "plan.md",
    "state": "unknown",
    "duplicate": false,
    "requestDigest": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "operationDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
    "expected": {
      "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "blobId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      "contentDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
    },
    "proposedContentDigest": "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
    "branch": "goobers/workbench/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "acceptedAt": "2026-10-04T12:00:00Z",
    "phases": [
      {
        "name": "tree",
        "outcome": "unknown",
        "claimedAt": "2026-10-04T12:00:00Z",
        "finishedAt": "2026-10-04T12:00:00Z"
      }
    ],
    "observations": [],
    "omittedObservations": 0,
    "nextAction": "Inspect the exact retained effect; do not retry the write."
  },
  "workbenchGraph": {
    "generation": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "gaggleId": "web",
    "nodes": [
      {
        "key": "f04c1f27b09ec0e4cdd82790f0b2d31a616386345f3bc8cae55b8eb9621404ea",
        "observations": [
          {
            "contentDigest": "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
            "ref": {
              "gaggleId": "web",
              "sourceBindingId": "backlog",
              "kind": "work-item",
              "sourceId": "987654"
            },
            "title": "Explicit native objective",
            "type": "Issue",
            "state": "open",
            "revision": "2026-10-04T12:00:00Z",
            "locator": {
              "id": "42"
            },
            "objective": true
          }
        ],
        "conflict": false
      }
    ],
    "edges": [
      {
        "key": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
        "edgeId": "edge-00000000-0000-0000-0000-000000000001",
        "kind": "contributes-to",
        "from": {
          "ref": {
            "gaggleId": "web",
            "sourceBindingId": "backlog",
            "kind": "work-item",
            "sourceId": "987654"
          },
          "resolved": true
        },
        "to": {
          "ref": {
            "gaggleId": "web",
            "sourceBindingId": "strategy",
            "kind": "objective-document",
            "sourceId": "obj-00000000-0000-0000-0000-000000000001"
          },
          "resolved": false
        },
        "origin": "authored",
        "owner": {
          "kind": "manifest",
          "sourceBindingId": "links",
          "path": "links.yaml"
        },
        "conflict": false
      }
    ],
    "documents": [
      {
        "sourceBindingId": "strategy",
        "path": "objective.md",
        "status": "available",
        "provenance": {
          "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          "blobId": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
          "contentDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
        },
        "ref": {
          "gaggleId": "web",
          "sourceBindingId": "strategy",
          "kind": "objective-document",
          "sourceId": "obj-00000000-0000-0000-0000-000000000001"
        }
      }
    ],
    "aliases": [
      {
        "name": "delivery",
        "target": {
          "ref": {
            "gaggleId": "web",
            "sourceBindingId": "strategy",
            "kind": "objective-document",
            "sourceId": "obj-00000000-0000-0000-0000-000000000001"
          },
          "resolved": false
        },
        "owner": {
          "kind": "manifest",
          "sourceBindingId": "links",
          "path": "links.yaml"
        }
      }
    ],
    "sources": [
      {
        "sourceBindingId": "backlog",
        "kind": "backlog",
        "status": "partial",
        "consistency": "native-non-snapshot",
        "sourceTargetDigest": "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
        "reasons": [
          "native-non-snapshot"
        ]
      }
    ],
    "conflicts": [],
    "partial": true
  },
  "workbenchDocuments": {
    "sourceBindingId": "strategy",
    "repository": {
      "provider": "github",
      "owner": "acme",
      "name": "plans"
    },
    "branch": "main",
    "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "sourceTargetDigest": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "files": [
      {
        "path": "objectives/reliability.md",
        "status": "available",
        "provenance": {
          "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
          "blobId": "cccccccccccccccccccccccccccccccccccccccc",
          "contentDigest": "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd"
        },
        "ref": {
          "gaggleId": "web",
          "sourceBindingId": "strategy",
          "kind": "objective-document",
          "sourceId": "obj-00000000-0000-0000-0000-000000000001"
        },
        "body": "# Reliability\nKeep work recoverable.\n",
        "objective": {
          "schemaVersion": "objectives/v1",
          "objectiveId": "obj-00000000-0000-0000-0000-000000000001",
          "title": "Reliable delivery",
          "edges": [
            {
              "edgeId": "edge-00000000-0000-0000-0000-000000000001",
              "kind": "contributes-to",
              "from": {
                "gaggleId": "web",
                "sourceBindingId": "backlog",
                "kind": "work-item",
                "sourceId": "987654"
              },
              "to": {
                "gaggleId": "web",
                "sourceBindingId": "strategy",
                "kind": "objective-document",
                "sourceId": "obj-00000000-0000-0000-0000-000000000001"
              },
              "rationale": "Explicit team objective"
            }
          ]
        }
      }
    ],
    "startOffset": 0,
    "totalPaths": 1,
    "exhausted": true,
    "coverage": "complete"
  },
  "workbenchSources": {
    "items": [
      {
        "bindingId": "backlog",
        "kind": "backlog",
        "provider": "github",
        "owner": "acme",
        "repository": "issues",
        "writeFields": [
          "title",
          "description"
        ]
      }
    ],
    "generation": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "workbenchItems": {
    "items": [
      {
        "ref": {
          "gaggleId": "web",
          "sourceBindingId": "backlog",
          "kind": "work-item",
          "sourceId": "987654"
        },
        "locator": {
          "id": "42",
          "url": "https://github.com/acme/issues/issues/42"
        },
        "revision": "2026-10-04T12:00:00Z",
        "revisionSemantics": "timestamp-preflight",
        "type": "Issue",
        "title": "Reliable processing",
        "state": "open",
        "objective": true,
        "relationshipCoverage": {
          "parents": "not-loaded",
          "blockers": "not-loaded",
          "milestones": "complete"
        }
      }
    ],
    "exhausted": true,
    "partial": false,
    "candidates": 1,
    "omitted": 0,
    "sourceTargetDigest": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
  },
  "workbenchItem": {
    "ref": {
      "gaggleId": "web",
      "sourceBindingId": "backlog",
      "kind": "work-item",
      "sourceId": "987654"
    },
    "locator": {
      "id": "42",
      "url": "https://github.com/acme/issues/issues/42"
    },
    "revision": "2026-10-04T12:00:00Z",
    "revisionSemantics": "timestamp-preflight",
    "type": "Issue",
    "title": "Reliable processing",
    "state": "open",
    "objective": true,
    "relationshipCoverage": {
      "parents": "not-loaded",
      "blockers": "not-loaded",
      "milestones": "complete"
    }
  },
  "sessionCreate": {
    "title": "Scope the next feature",
    "goober": "planner"
  },
  "sessionInput": {
    "text": "Outline the work and open questions."
  },
  "sessionClose": {
    "reason": "Scoping complete."
  },
  "session": {
    "id": "session-one",
    "gaggle": "web",
    "title": "Scope the next feature",
    "goober": "planner",
    "configGeneration": "generation-one",
    "gooberDigest": "digest-one",
    "state": "queued",
    "createdBy": {
      "issuer": "https://identity.example",
      "subject": "alice"
    },
    "createdAt": "2026-10-04T12:00:00Z",
    "updatedAt": "2026-10-04T12:00:00Z",
    "nextSequence": 2
  },
  "sessions": {
    "items": [
      {
        "id": "session-one",
        "gaggle": "web",
        "title": "Scope the next feature",
        "goober": "planner",
        "configGeneration": "generation-one",
        "gooberDigest": "digest-one",
        "state": "queued",
        "createdBy": {
          "issuer": "https://identity.example",
          "subject": "alice"
        },
        "createdAt": "2026-10-04T12:00:00Z",
        "updatedAt": "2026-10-04T12:00:00Z",
        "nextSequence": 2
      }
    ]
  },
  "sessionMessages": {
    "items": [
      {
        "id": "message-one",
        "sessionId": "session-one",
        "sequence": 1,
        "actorKind": "human",
        "actor": {
          "issuer": "https://identity.example",
          "subject": "alice"
        },
        "text": "Outline the work and open questions.",
        "createdAt": "2026-10-04T12:00:00Z",
        "turnId": "turn-one"
      }
    ]
  },
  "sessionAccepted": {
    "session": {
      "id": "session-one",
      "gaggle": "web",
      "title": "Scope the next feature",
      "goober": "planner",
      "configGeneration": "generation-one",
      "gooberDigest": "digest-one",
      "state": "queued",
      "createdBy": {
        "issuer": "https://identity.example",
        "subject": "alice"
      },
      "createdAt": "2026-10-04T12:00:00Z",
      "updatedAt": "2026-10-04T12:00:00Z",
      "nextSequence": 2
    },
    "message": {
      "id": "message-one",
      "sessionId": "session-one",
      "sequence": 1,
      "actorKind": "human",
      "actor": {
        "issuer": "https://identity.example",
        "subject": "alice"
      },
      "text": "Outline the work and open questions.",
      "createdAt": "2026-10-04T12:00:00Z",
      "turnId": "turn-one"
    },
    "acceptanceId": "accepted-one",
    "duplicate": false
  },
  "workbenchWriteCapabilities": {
    "fields": [
      "title",
      "description"
    ],
    "relationships": [],
    "revisionSemantics": "timestamp-preflight",
    "maxAssignees": 10,
    "controlLabelChanges": false
  },
  "workbenchPatch": {
    "sourceId": "987654",
    "expectedRevision": "2026-10-04T11:59:00Z",
    "field": "title",
    "value": "Clarify the human surface"
  },
  "workbenchCommand": {
    "id": "workbench-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "gaggle": "web",
    "sourceBindingId": "backlog",
    "actor": {
      "issuer": "https://identity.example",
      "subject": "alice"
    },
    "itemId": "42",
    "sourceId": "987654",
    "field": "title",
    "state": "unknown",
    "duplicate": false,
    "requestDigest": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
    "operationDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
    "acceptedAt": "2026-10-04T12:00:00Z",
    "attemptedAt": "2026-10-04T12:00:00Z",
    "completedAt": "2026-10-04T12:00:00Z",
    "receipt": {
      "operationDigest": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
      "outcome": "unknown",
      "revisionSemantics": "timestamp-preflight",
      "providerAcknowledged": false,
      "observedMatches": true,
      "observed": {
        "ref": {
          "gaggleId": "web",
          "sourceBindingId": "backlog",
          "kind": "work-item",
          "sourceId": "987654"
        },
        "locator": {
          "id": "42",
          "url": "https://github.com/acme/issues/issues/42"
        },
        "revision": "2026-10-04T12:00:00Z",
        "revisionSemantics": "timestamp-preflight",
        "type": "Issue",
        "title": "Reliable processing",
        "state": "open",
        "objective": true,
        "relationshipCoverage": {
          "parents": "not-loaded",
          "blockers": "not-loaded",
          "milestones": "complete"
        }
      }
    },
    "nextAction": "Inspect the source. Do not retry the write."
  },
  "childPublicationCheck": {
    "action": "pr",
    "expectedIntentDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "childPublicationResult": {
    "runId": "child-run",
    "requestId": "human-one",
    "publication": {
      "sourceRunId": "original-child",
      "executionEpoch": 0,
      "observation": "not_observed",
      "action": "pr",
      "intentDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "state": "effect_pending",
      "head": "goobers/children/child-run",
      "base": "main",
      "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      "needsHuman": true,
      "createdAt": "2026-10-04T12:00:00Z",
      "updatedAt": "2026-10-04T12:00:00Z"
    }
  },
  "childWorkflowPage": {
    "executionHistory": [
      {
        "epoch": 1,
        "runId": "current-child",
        "runAvailable": true,
        "current": true,
        "state": "running",
        "sourceRunId": "original-child",
        "actor": "issuer:alice",
        "stage": "repair",
        "acceptedAt": "2026-10-04T12:00:00Z",
        "updatedAt": "2026-10-04T12:00:00Z"
      }
    ],
    "publicationRunId": "original-child",
    "publications": [
      {
        "sourceRunId": "original-child",
        "executionEpoch": 0,
        "observation": "not_observed",
        "action": "pr",
        "intentDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "state": "effect_pending",
        "head": "goobers/children/child-run",
        "base": "main",
        "commit": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
        "needsHuman": true,
        "createdAt": "2026-10-04T12:00:00Z",
        "updatedAt": "2026-10-04T12:00:00Z"
      }
    ],
    "runId": "current-child",
    "gaggle": "web",
    "parent": {
      "runId": "parent-run",
      "workflow": "build",
      "invocationKey": "inspect"
    },
    "children": []
  },
  "interactiveRun": {
    "runId": "0123456789abcdef0123456789abcdef",
    "gaggle": "web",
    "phase": "running",
    "actions": [
      {
        "kind": "approve",
        "stage": "review",
        "subjectSequence": 4,
        "decisions": [
          "pass"
        ],
        "available": true,
        "reason": ""
      }
    ],
    "guidance": [],
    "restartReason": "Stage restart is not available."
  },
  "interactiveRunCommand": {
    "kind": "approve",
    "stage": "review",
    "expectedSubjectSequence": 4,
    "decision": "pass"
  },
  "interactiveRunResult": {
    "status": "applied",
    "accepted": true,
    "runId": "0123456789abcdef0123456789abcdef",
    "journalSequence": 6,
    "phase": "complete"
  },
  "interactiveCapabilities": {
    "gaggle": "web",
    "policyConfigured": true,
    "viewer": true,
    "operator": false,
    "sourceWriteMode": "pull-request",
    "actions": [
      {
        "action": "backlog.read",
        "authorized": true,
        "credentialConfigured": true,
        "available": false,
        "reasonCode": "operation_not_implemented"
      }
    ]
  },
  "childWorkflowSource": {
    "source": "kind: Workflow\n"
  },
  "childWorkflowResolve": {
    "invocationKey": "inspect-1",
    "action": "merge",
    "resultRef": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  },
  "childWorkflowResolution": {
    "invocationKey": "inspect-1",
    "action": "merge",
    "resultRef": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "requestedAt": "2026-10-04T12:00:00Z",
    "applied": false,
    "requestDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "planPublished": false
  },
  "childWorkflowStatus": {
    "invocationKey": "inspect-1"
  },
  "childWorkflowValidation": {
    "valid": false,
    "advisory": true,
    "diagnostics": [
      {
        "code": "schema",
        "field": "dslVersion",
        "message": "explicit DSL 3.1 is required"
      }
    ]
  },
  "childWorkflow": {
    "childId": "child-1",
    "acceptanceId": "trigger-1",
    "runId": "run-1",
    "invocationKey": "inspect-1",
    "sequence": 1,
    "state": "queued",
    "sourceDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "canonicalDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "configDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "policyDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "workflowDigest": "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
    "cancellationRequested": false,
    "acknowledged": false,
    "acceptedAt": "2026-10-04T12:00:00Z",
    "updatedAt": "2026-10-04T12:00:00Z"
  },
  "triggerRequest": {
    "gaggle": "goobers",
    "workflow": "implement",
    "requestId": "delivery-1",
    "sourceRun": "source-1"
  },
  "triggerResponse": {
    "acceptanceId": "trigger-0123456789abcdef0123456789abcdef",
    "state": "accepted",
    "duplicate": true
  },
  "triggerStatus": {
    "acceptanceId": "trigger-0123456789abcdef0123456789abcdef",
    "state": "dispatched",
    "runId": "0123456789abcdef0123456789abcdef",
    "acceptedAt": "2026-07-18T12:34:56Z"
  },
  "cancelRequest": {
    "workflow": "implement",
    "gaggle": "goobers",
    "actor": "operator"
  },
  "cancelResult": {
    "code": "cancellation_requested"
  },
  "operatorMessageRequest": {
    "gaggle": "goobers",
    "targetAddress": "terminal:operator",
    "purpose": "approval-required",
    "content": {
      "text": "Please review the run."
    },
    "deliveryMode": "terminal"
  },
  "operatorMessageResponse": {
    "accepted": true,
    "record": {
      "request": {
        "schema": "goobers.dev/operator-message/request/v1",
        "requestId": "message-1",
        "idempotencyKey": "key-1",
        "targetAddress": "terminal:operator",
        "principalRef": "user:operator",
        "requestedAt": "2026-07-18T12:34:56Z",
        "purpose": "approval-required",
        "content": {
          "text": "Please review the run."
        },
        "deliveryMode": "terminal"
      },
      "state": "accepted"
    }
  },
  "queueEligibility": {
    "gaggle": "goobers",
    "workflow": "review",
    "asOf": "2026-07-18T12:34:56Z",
    "status": "observed",
    "sourceRunId": "queue-run",
    "sourceStage": "select",
    "report": {
      "version": 1,
      "repositoryKey": "github|||org|repo|",
      "gaggle": "goobers",
      "workflow": "review",
      "runId": "queue-run",
      "observedAt": "2026-07-18T12:34:56Z",
      "completeSnapshot": true,
      "matchingItems": 1,
      "omittedItems": 0,
      "items": [
        {
          "number": 42,
          "eligible": false,
          "reason": "escalated, human action required",
          "nextStep": "Human review and an explicit retry are required after the escalation cause is resolved.",
          "claim": {
            "state": "unknown",
            "providerClaimLabel": false,
            "comparison": "unavailable",
            "nextStep": "Restore access to the claim ledger before inferring claim availability."
          }
        }
      ]
    }
  },
  "health": {
    "selfExecution": {
      "policy": "",
      "observed": false,
      "placements": 0,
      "refusals": 0
    },
    "apiVersion": "v1",
    "schemaVersion": "v1",
    "build": {
      "version": "v1.2.3",
      "commit": "abc1234",
      "date": "2026-07-18T12:00:00Z"
    },
    "ready": true,
    "healthy": true,
    "instance": {
      "name": "fixture",
      "environment": "dev"
    },
    "freshness": {
      "observedAt": "2026-07-18T12:34:56Z",
      "definitionsLoadedAt": "2026-07-18T12:32:56Z",
      "journalUpdatedAt": null,
      "lastSchedulerTickAt": "2026-07-18T12:32:56Z",
      "lastTickAgeMillis": 120000
    },
    "definitionReload": {
      "appliedDigest": "sha256:applied",
      "observedDigest": "sha256:observed",
      "observedAt": "2026-07-18T12:34:56Z",
      "watching": true,
      "state": "rejected"
    },
    "update": {
      "available": true,
      "latestVersion": "v1.3.0",
      "currentVersion": "v1.2.3",
      "channel": "stable",
      "checkedAt": "2026-07-18T12:34:56Z"
    },
    "telemetryExporterHealth": {
      "destinations": {
        "collector": {
          "enabled": true,
          "mode": "otlp",
          "trace": {
            "configured": true,
            "state": "healthy",
            "lastSuccessAt": "2026-07-18T12:36:56Z",
            "lastFailureAt": "2026-07-18T12:32:56Z",
            "lastFailureReason": "collector_unavailable",
            "lastTransitionAt": "2026-07-18T12:36:56Z",
            "recoveryTransitions": 1,
            "failureTransitions": 1,
            "suppressedFailureEvents": 2
          },
          "metric": {
            "configured": true,
            "state": "unhealthy",
            "lastFailureAt": "2026-07-18T12:36:56Z",
            "lastFailureReason": "signal_unimplemented",
            "consecutiveFailures": 3,
            "lastTransitionAt": "2026-07-18T12:36:56Z",
            "failureTransitions": 1,
            "suppressedFailureEvents": 2
          }
        },
        "tenant": {
          "replay": {
            "accountingReady": true,
            "pendingRecords": 2,
            "pendingBytes": 1024,
            "oldestPendingSeconds": 30,
            "lastSuccess": "2026-07-18T12:32:56Z",
            "lastFailure": "2026-07-18T12:36:56Z",
            "failureClass": "rejected",
            "activeFailure": true
          },
          "journal": {
            "accepted": 12,
            "dropped": 0,
            "failures": 0
          },
          "diagnostics": {
            "accepted": 3,
            "dropped": 0,
            "failures": 0
          },
          "enabled": true,
          "mode": "azure-monitor",
          "trace": {
            "configured": true,
            "state": "healthy",
            "lastSuccessAt": "2026-07-18T12:36:56Z"
          },
          "metric": {
            "configured": false,
            "state": "disabled"
          }
        }
      },
      "enabled": true,
      "mode": "custom",
      "trace": {
        "configured": true,
        "state": "healthy",
        "lastSuccessAt": "2026-07-18T12:36:56Z",
        "lastFailureAt": "2026-07-18T12:32:56Z",
        "lastFailureReason": "collector_unavailable",
        "lastTransitionAt": "2026-07-18T12:36:56Z",
        "recoveryTransitions": 1,
        "failureTransitions": 1,
        "suppressedFailureEvents": 2
      },
      "metric": {
        "configured": true,
        "state": "unhealthy",
        "lastFailureAt": "2026-07-18T12:36:56Z",
        "lastFailureReason": "signal_unimplemented",
        "consecutiveFailures": 3,
        "lastTransitionAt": "2026-07-18T12:36:56Z",
        "failureTransitions": 1,
        "suppressedFailureEvents": 2
      }
    }
  },
  "instance": {
    "apiVersion": "v1",
    "schemaVersion": "v1",
    "name": "fixture",
    "environment": "dev",
    "instanceRoot": "/instances/fixture",
    "ready": true,
    "status": "degraded",
    "concurrency": {
      "activeRuns": 1,
      "maxConcurrentRuns": 4
    },
    "counts": {
      "gaggles": 1,
      "goobers": 1,
      "workflows": 1,
      "activeRuns": 1
    },
    "warnings": [
      {
        "code": "VER001",
        "severity": "warning",
        "scope": "Workflow/implementation",
        "explanation": "fixture warning"
      }
    ],
    "telemetryRetention": {
      "enabled": true,
      "window": "90d",
      "maxRuns": 500,
      "firstEnable": "gracePeriod",
      "enforceAt": "2026-07-18T12:36:56Z",
      "lastPassAt": "2026-07-18T12:32:56Z",
      "lastPassMode": "dry-run",
      "candidateCount": 7
    },
    "journalHealth": {
      "appendsDropped": 2
    },
    "storageHealth": {
      "tier": "admission-stopped",
      "path": "/instances/fixture",
      "freeBytes": 1073741824,
      "totalBytes": 107374182400,
      "warningFloorBytes": 10737418240,
      "criticalFloorBytes": 5368709120,
      "measuredAt": "2026-07-18T12:32:56Z"
    },
    "telemetryExporterHealth": {
      "destinations": {
        "collector": {
          "enabled": true,
          "mode": "otlp",
          "trace": {
            "configured": true,
            "state": "healthy",
            "lastSuccessAt": "2026-07-18T12:36:56Z",
            "lastFailureAt": "2026-07-18T12:32:56Z",
            "lastFailureReason": "collector_unavailable",
            "lastTransitionAt": "2026-07-18T12:36:56Z",
            "recoveryTransitions": 1,
            "failureTransitions": 1,
            "suppressedFailureEvents": 2
          },
          "metric": {
            "configured": true,
            "state": "unhealthy",
            "lastFailureAt": "2026-07-18T12:36:56Z",
            "lastFailureReason": "signal_unimplemented",
            "consecutiveFailures": 3,
            "lastTransitionAt": "2026-07-18T12:36:56Z",
            "failureTransitions": 1,
            "suppressedFailureEvents": 2
          }
        },
        "tenant": {
          "replay": {
            "accountingReady": true,
            "pendingRecords": 2,
            "pendingBytes": 1024,
            "oldestPendingSeconds": 30,
            "lastSuccess": "2026-07-18T12:32:56Z",
            "lastFailure": "2026-07-18T12:36:56Z",
            "failureClass": "rejected",
            "activeFailure": true
          },
          "journal": {
            "accepted": 12,
            "dropped": 0,
            "failures": 0
          },
          "diagnostics": {
            "accepted": 3,
            "dropped": 0,
            "failures": 0
          },
          "enabled": true,
          "mode": "azure-monitor",
          "trace": {
            "configured": true,
            "state": "healthy",
            "lastSuccessAt": "2026-07-18T12:36:56Z"
          },
          "metric": {
            "configured": false,
            "state": "disabled"
          }
        }
      },
      "enabled": true,
      "mode": "custom",
      "trace": {
        "configured": true,
        "state": "healthy",
        "lastSuccessAt": "2026-07-18T12:36:56Z",
        "lastFailureAt": "2026-07-18T12:32:56Z",
        "lastFailureReason": "collector_unavailable",
        "lastTransitionAt": "2026-07-18T12:36:56Z",
        "recoveryTransitions": 1,
        "failureTransitions": 1,
        "suppressedFailureEvents": 2
      },
      "metric": {
        "configured": true,
        "state": "unhealthy",
        "lastFailureAt": "2026-07-18T12:36:56Z",
        "lastFailureReason": "signal_unimplemented",
        "consecutiveFailures": 3,
        "lastTransitionAt": "2026-07-18T12:36:56Z",
        "failureTransitions": 1,
        "suppressedFailureEvents": 2
      }
    },
    "recoveryInventory": {
      "state": "warning",
      "used": 104,
      "limit": 128,
      "unreadable": 2,
      "overflow": 0,
      "highWaterPercent": 80,
      "earliestRetainUntil": "2026-07-18T12:36:56Z",
      "inventoryRoot": "/instances/fixture/recovery",
      "policySource": "instance-config",
      "observedAt": "2026-07-18T12:32:56Z"
    },
    "memoryGateEnabled": false,
    "fsyncDisabled": false,
    "fleetEnrolled": false
  },
  "portalConfig": {
    "brand": {
      "name": "goobers",
      "tagline": "local operations",
      "scopeMark": "G",
      "logoUrl": null,
      "faviconUrl": null
    },
    "theme": {
      "accentLight": null,
      "accentDark": null,
      "accentSoftLight": null,
      "accentSoftDark": null,
      "accentInkLight": null,
      "accentInkDark": null
    },
    "support": {
      "docsUrl": null,
      "issuesUrl": null,
      "chatUrl": null,
      "links": []
    },
    "capabilities": {
      "revealRun": false,
      "workflowEnable": false
    }
  },
  "gaggles": {
    "items": [
      {
        "template": {
          "state": "update-available",
          "installed": "1111111111111111111111111111111111111111",
          "candidate": "2222222222222222222222222222222222222222",
          "checkedAt": "2026-07-18T12:34:56Z",
          "lastSuccess": "2026-07-18T12:34:56Z",
          "changes": [
            "workflows/implementation.yaml"
          ],
          "pendingBackprop": true
        },
        "name": "core",
        "displayName": "Core",
        "enabled": false,
        "status": "configured",
        "project": {
          "provider": "github",
          "owner": "Agent-Clubhouse",
          "name": "Goobers",
          "branch": "main",
          "connectionRef": "github"
        },
        "backlog": {
          "provider": "github",
          "project": "Agent-Clubhouse/Goobers",
          "labels": [
            "goobers:ready"
          ],
          "connectionRef": "github"
        },
        "gooberCount": 1,
        "workflowCount": 1,
        "activeRunCount": 1,
        "warnings": [
          {
            "code": "VER001",
            "severity": "warning",
            "scope": "Workflow/implementation",
            "explanation": "fixture warning"
          }
        ]
      }
    ],
    "page": {
      "limit": 50,
      "total": 1,
      "hasMore": true,
      "nextCursor": "next-page"
    }
  },
  "goobers": {
    "items": [
      {
        "name": "implementer",
        "displayName": "Implementer",
        "role": "coder",
        "status": "configured",
        "harness": "claude-code",
        "skills": [
          "go"
        ],
        "capabilities": [
          "repo:push"
        ],
        "workflows": [
          {
            "gaggle": "core",
            "name": "implementation"
          }
        ],
        "stages": [
          {
            "workflow": {
              "gaggle": "core",
              "name": "implementation"
            },
            "stage": "implement",
            "kind": "agentic"
          }
        ],
        "warnings": [
          {
            "code": "VER001",
            "severity": "warning",
            "scope": "Workflow/implementation",
            "explanation": "fixture warning"
          }
        ]
      }
    ],
    "page": {
      "limit": 50,
      "total": 1,
      "hasMore": true,
      "nextCursor": "next-page"
    }
  },
  "workflows": {
    "items": [
      {
        "engineFallback": {
          "gaggle": "core",
          "workflow": "implementation",
          "runId": "run-1",
          "at": "2026-09-07T00:00:00Z",
          "reason": "implement is self-pinned",
          "reasonClass": "placement_ineligible",
          "placementDeclared": true,
          "selfPinnedStages": [
            "implement"
          ],
          "unpinnedGates": [
            "review"
          ]
        },
        "identity": {
          "gaggle": "core",
          "name": "implementation"
        },
        "displayName": "Implementation",
        "enabled": false,
        "purpose": "Implement an approved backlog item.",
        "triggers": [
          {
            "type": "backlog-item",
            "selector": {
              "label": "approved"
            }
          },
          {
            "type": "schedule",
            "schedule": "0 * * * *"
          },
          {
            "type": "signal",
            "signal": "backlog-ready"
          },
          {
            "type": "webhook",
            "events": [
              "issues"
            ]
          }
        ],
        "readiness": {
          "maxConcurrentRuns": 1,
          "maxRunsPerHour": 10,
          "maxRunsPerDay": 20,
          "maxChainDepth": 3,
          "maxOpenPRs": 2
        },
        "concurrency": {
          "activeRuns": 1,
          "maxConcurrentRuns": 2
        },
        "owners": [
          {
            "gaggle": "core",
            "name": "implementer"
          }
        ],
        "stageCount": 2,
        "definition": {
          "version": 7,
          "digest": "sha256:workflow"
        },
        "backprop": {
          "enabled": true,
          "version": "v1"
        },
        "warnings": [
          {
            "code": "VER001",
            "severity": "warning",
            "scope": "Workflow/implementation",
            "explanation": "fixture warning"
          }
        ]
      }
    ],
    "page": {
      "limit": 50,
      "total": 1,
      "hasMore": true,
      "nextCursor": "next-page"
    }
  },
  "workflowDetail": {
    "engineFallback": {
      "gaggle": "core",
      "workflow": "implementation",
      "runId": "run-1",
      "at": "2026-09-07T00:00:00Z",
      "reason": "implement is self-pinned",
      "reasonClass": "placement_ineligible",
      "placementDeclared": true,
      "selfPinnedStages": [
        "implement"
      ],
      "unpinnedGates": [
        "review"
      ]
    },
    "identity": {
      "gaggle": "core",
      "name": "implementation"
    },
    "displayName": "Implementation",
    "enabled": false,
    "purpose": "Implement an approved backlog item.",
    "triggers": [
      {
        "type": "backlog-item",
        "selector": {
          "label": "approved"
        }
      },
      {
        "type": "schedule",
        "schedule": "0 * * * *"
      },
      {
        "type": "signal",
        "signal": "backlog-ready"
      },
      {
        "type": "webhook",
        "events": [
          "issues"
        ]
      }
    ],
    "readiness": {
      "maxConcurrentRuns": 1,
      "maxRunsPerHour": 10,
      "maxRunsPerDay": 20,
      "maxChainDepth": 3,
      "maxOpenPRs": 2
    },
    "concurrency": {
      "activeRuns": 1,
      "maxConcurrentRuns": 2
    },
    "owners": [
      {
        "gaggle": "core",
        "name": "implementer"
      }
    ],
    "stageCount": 2,
    "definition": {
      "version": 7,
      "digest": "sha256:workflow"
    },
    "backprop": {
      "enabled": true,
      "version": "v1"
    },
    "warnings": [
      {
        "code": "VER001",
        "severity": "warning",
        "scope": "Workflow/implementation",
        "explanation": "fixture warning"
      }
    ],
    "graph": {
      "name": "implementation",
      "version": 7,
      "digest": "sha256:workflow",
      "start": "implement",
      "nodes": [
        {
          "id": "implement",
          "kind": "agentic",
          "owner": "implementer"
        },
        {
          "id": "review",
          "kind": "gate",
          "evaluator": "agentic"
        }
      ],
      "edges": [
        {
          "source": "implement",
          "target": "review"
        },
        {
          "source": "review",
          "target": "@escalate",
          "outcome": "fail",
          "terminal": "escalate"
        }
      ]
    },
    "stages": [
      {
        "name": "implement",
        "kind": "agentic",
        "goal": "Implement the claimed item.",
        "owner": {
          "gaggle": "core",
          "name": "implementer"
        },
        "evaluator": "",
        "capabilities": [
          "repo:push"
        ],
        "timeoutSeconds": 3600,
        "retry": {
          "maxAttempts": 2,
          "backoffSeconds": 30
        },
        "policyActions": [
          "pr:open"
        ],
        "rawYaml": "name: implement\ntype: agentic\ngoober: implementer\ngoal: Implement the claimed item.\ncapabilities:\n- repo:push\npolicyActions:\n- pr:open\nretry:\n  maxAttempts: 2\n  backoffSeconds: 30\ntimeoutSeconds: 3600\n"
      },
      {
        "name": "review",
        "kind": "gate",
        "goal": "Review the implementation.",
        "owner": null,
        "evaluator": "agentic",
        "capabilities": [
          "repo:read"
        ],
        "branches": {
          "needs-changes": "implement",
          "pass": ""
        },
        "rawYaml": "name: review\nevaluator: agentic\nagentic:\n  goober: implementer\nbranches:\n  pass: \"\"\n  needs-changes: implement\n"
      }
    ]
  },
  "runs": {
    "runs": [
      {
        "retryBackoff": {},
        "activeStages": [
          {
            "name": "implement",
            "kind": "stage",
            "branch": 1,
            "attempt": 2,
            "goober": "implementer",
            "startedAt": "2026-07-18T12:32:56Z"
          }
        ],
        "activityTruncated": true,
        "engineFallback": {
          "gaggle": "core",
          "workflow": "implementation",
          "runId": "run-1",
          "at": "2026-09-07T00:00:00Z",
          "reason": "implement is self-pinned",
          "reasonClass": "placement_ineligible",
          "placementDeclared": true,
          "selfPinnedStages": [
            "implement"
          ],
          "unpinnedGates": [
            "review"
          ]
        },
        "id": "run-123",
        "workflow": "implementation",
        "workflowVersion": 7,
        "workflowDigest": "sha256:workflow",
        "gaggle": "core",
        "trigger": {
          "kind": "item",
          "ref": "673"
        },
        "phase": "escalated",
        "terminal": true,
        "currentStage": "review",
        "startedAt": "2026-07-18T12:32:56Z",
        "finishedAt": "2026-07-18T12:36:56Z",
        "durationMillis": 120000,
        "lastActivityAt": "2026-07-18T12:36:56Z",
        "stale": false,
        "lastSeq": 16,
        "repassCount": 2,
        "retryCount": 2,
        "policyRetryCount": 1,
        "infraRetryCount": 1,
        "lineage": {
          "source": {
            "id": "run-122",
            "phase": "failed"
          },
          "continuations": [
            {
              "id": "run-124",
              "phase": "running"
            }
          ],
          "resumeTarget": "implement",
          "workspaceBranch": "goobers/implementation/run-122",
          "workspaceBranchSha": "abc123",
          "historicalRepassCount": 2
        },
        "noWork": false,
        "operator": {
          "issue": {
            "number": "673",
            "title": "Improve operator status"
          },
          "currentStage": "review",
          "liveness": "terminal",
          "trajectory": "terminal",
          "claim": {
            "leaseStatus": "released",
            "providerMarker": "recorded"
          },
          "potentialBlockers": []
        }
      }
    ],
    "workflowActivity": [
      {
        "gaggle": "core",
        "workflow": "implementation",
        "activeRuns": 1
      }
    ],
    "nextCursor": "next-run"
  },
  "runDetail": {
    "retryBackoff": {},
    "activeStages": [
      {
        "name": "implement",
        "kind": "stage",
        "branch": 1,
        "attempt": 2,
        "goober": "implementer",
        "startedAt": "2026-07-18T12:32:56Z"
      }
    ],
    "activityTruncated": true,
    "engineFallback": {
      "gaggle": "core",
      "workflow": "implementation",
      "runId": "run-1",
      "at": "2026-09-07T00:00:00Z",
      "reason": "implement is self-pinned",
      "reasonClass": "placement_ineligible",
      "placementDeclared": true,
      "selfPinnedStages": [
        "implement"
      ],
      "unpinnedGates": [
        "review"
      ]
    },
    "id": "run-123",
    "workflow": "implementation",
    "workflowVersion": 7,
    "workflowDigest": "sha256:workflow",
    "gaggle": "core",
    "trigger": {
      "kind": "item",
      "ref": "673"
    },
    "phase": "escalated",
    "terminal": true,
    "currentStage": "review",
    "startedAt": "2026-07-18T12:32:56Z",
    "finishedAt": "2026-07-18T12:36:56Z",
    "durationMillis": 120000,
    "lastActivityAt": "2026-07-18T12:36:56Z",
    "stale": false,
    "lastSeq": 16,
    "repassCount": 2,
    "retryCount": 2,
    "policyRetryCount": 1,
    "infraRetryCount": 1,
    "lineage": {
      "source": {
        "id": "run-122",
        "phase": "failed"
      },
      "continuations": [
        {
          "id": "run-124",
          "phase": "running"
        }
      ],
      "resumeTarget": "implement",
      "workspaceBranch": "goobers/implementation/run-122",
      "workspaceBranchSha": "abc123",
      "historicalRepassCount": 2
    },
    "noWork": false,
    "operator": {
      "issue": {
        "number": "673",
        "title": "Improve operator status"
      },
      "currentStage": "review",
      "liveness": "terminal",
      "trajectory": "terminal",
      "claim": {
        "leaseStatus": "released",
        "providerMarker": "recorded"
      },
      "potentialBlockers": []
    },
    "graph": {
      "name": "implementation",
      "version": 7,
      "digest": "sha256:workflow",
      "start": "implement",
      "nodes": [
        {
          "id": "implement",
          "kind": "agentic",
          "owner": "implementer"
        },
        {
          "id": "review",
          "kind": "gate",
          "evaluator": "agentic"
        }
      ],
      "edges": [
        {
          "source": "implement",
          "target": "review"
        },
        {
          "source": "review",
          "target": "@escalate",
          "outcome": "fail",
          "terminal": "escalate"
        }
      ]
    },
    "graphStatus": "pinned",
    "escalation": {
      "selector": {
        "kind": "gate",
        "name": "review"
      },
      "selectedBranch": "fail",
      "repassCount": 1,
      "retryCount": 2,
      "terminalReason": "review budget exhausted",
      "causalEventSeq": 9
    },
    "terminalCauseStatus": "unavailable",
    "transitions": [
      {
        "branch": 0,
        "occurrence": 0,
        "seq": 3,
        "source": "implement",
        "target": "review"
      },
      {
        "branch": 0,
        "occurrence": 0,
        "seq": 9,
        "source": "review",
        "verdict": "fail",
        "terminal": true,
        "status": "escalated"
      }
    ],
    "transitionsStatus": "projected"
  },
  "runEvents": {
    "runId": "run-123",
    "events": [
      {
        "schema": "goobers.dev/run-event/v1",
        "seq": 9,
        "type": "stage.finished",
        "branch": 0,
        "time": "2026-07-18T12:36:56Z",
        "knownSchema": true,
        "category": "transition",
        "replayChapter": true,
        "stage": "implement",
        "attempt": 2,
        "attemptClass": "policy",
        "gate": "review",
        "verdict": "needs-changes",
        "target": "implement",
        "escalated": true,
        "status": "success",
        "outputs": {
          "approved": true,
          "score": 0.98
        },
        "artifacts": [
          {
            "name": "result",
            "digest": "sha256:artifact",
            "size": 42,
            "mediaType": "application/json",
            "stage": "implement",
            "attempt": 2,
            "attemptClass": "policy",
            "recordedSeq": 8
          }
        ],
        "artifact": {
          "name": "result",
          "digest": "sha256:artifact",
          "size": 42,
          "mediaType": "application/json",
          "stage": "implement",
          "attempt": 2,
          "attemptClass": "policy",
          "recordedSeq": 8
        },
        "name": "result",
        "externalRef": {
          "provider": "github",
          "kind": "issue",
          "id": "673",
          "url": "https://github.com/Agent-Clubhouse/Goobers/issues/673"
        },
        "error": {
          "code": "review_failed",
          "message": "review requested changes",
          "causes": [
            {
              "message": "review gate failed"
            },
            {
              "code": "review_rejected",
              "message": "review requested changes"
            }
          ]
        },
        "redaction": {
          "target": "artifacts/result.json",
          "oldDigest": "sha256:old",
          "newDigest": "sha256:new",
          "reason": "secret remediation"
        },
        "runner": {
          "worker": "local"
        },
        "workflow": "implementation",
        "runId": "run-123",
        "reason": "fixture",
        "parallel": "fanout",
        "branchName": "security-lens",
        "branchStatus": "succeeded",
        "completeness": [
          {
            "branch": 1,
            "name": "security-lens",
            "status": "succeeded",
            "artifacts": 1
          },
          {
            "branch": 2,
            "name": "perf-lens",
            "status": "failed",
            "artifacts": 0
          }
        ],
        "raw": {
          "futureField": "preserved"
        }
      }
    ]
  },
  "stageAttempts": {
    "runId": "run-123",
    "stage": "implement",
    "attempts": [
      {
        "id": "sta_visit_1_attempt_1",
        "visit": 1,
        "number": 1,
        "class": "initial",
        "status": "failure",
        "startedSeq": 2,
        "finishedSeq": 3,
        "startedAt": "2026-07-18T12:32:56Z",
        "finishedAt": "2026-07-18T12:36:56Z",
        "durationMillis": 120000,
        "artifacts": [],
        "error": {
          "code": "initial_failed",
          "message": "initial execution failed"
        }
      },
      {
        "id": "sta_visit_1_attempt_2",
        "visit": 1,
        "number": 2,
        "class": "policy",
        "status": "success",
        "placement": {
          "runner": "self",
          "node": "aks-linux-0001",
          "host": "goobers-stage-implement-4x2vq",
          "os": "linux",
          "image": "ghcr.io/goobers/goobers-base:v0.2.0",
          "pod": "goobers-stage-implement-4x2vq",
          "queuedAt": "2026-07-18T12:32:56Z",
          "podStartedAt": "2026-07-18T12:32:56Z"
        },
        "startedSeq": 4,
        "finishedSeq": 8,
        "startedAt": "2026-07-18T12:32:56Z",
        "finishedAt": "2026-07-18T12:36:56Z",
        "durationMillis": 120000,
        "outputs": {
          "summary": "implemented"
        },
        "artifacts": [
          {
            "name": "result",
            "digest": "sha256:artifact",
            "size": 42,
            "mediaType": "application/json",
            "stage": "implement",
            "attempt": 2,
            "attemptClass": "policy",
            "recordedSeq": 8
          }
        ]
      },
      {
        "id": "sta_visit_2_attempt_1",
        "visit": 2,
        "number": 1,
        "class": "initial",
        "status": "failure",
        "startedSeq": 10,
        "finishedSeq": 11,
        "startedAt": "2026-07-18T12:32:56Z",
        "finishedAt": "2026-07-18T12:36:56Z",
        "durationMillis": 120000,
        "artifacts": [],
        "error": {
          "code": "repass_failed",
          "message": "first repass failed"
        }
      },
      {
        "id": "sta_visit_2_attempt_2",
        "visit": 2,
        "number": 2,
        "class": "infra",
        "status": "success",
        "startedSeq": 12,
        "finishedSeq": 13,
        "startedAt": "2026-07-18T12:32:56Z",
        "finishedAt": "2026-07-18T12:36:56Z",
        "durationMillis": 120000,
        "artifacts": []
      },
      {
        "id": "sta_visit_3_attempt_1",
        "visit": 3,
        "number": 1,
        "class": "initial",
        "status": "running",
        "startedSeq": 15,
        "startedAt": "2026-07-18T12:32:56Z",
        "durationMillis": 0,
        "artifacts": []
      }
    ]
  },
  "telemetryCosts": {
    "provider": "github",
    "scope": "summary",
    "since": "2026-07-18T12:32:56Z",
    "until": "2026-07-18T12:34:56Z",
    "pullRequests": [
      {
        "provider": "github",
        "externalKind": "pr",
        "externalId": "4398",
        "totalRuns": 3,
        "measuredRuns": 2,
        "totalAttempts": 4,
        "measuredAttempts": 3,
        "inputTokens": 36000,
        "outputTokens": 12000,
        "nativeTotals": [
          {
            "unit": "aiCredits",
            "value": 2.5,
            "estimated": false
          }
        ],
        "normalizedTotals": [
          {
            "unit": "usd",
            "value": 0.025,
            "estimated": true
          }
        ],
        "billingModels": [
          "ai_credits"
        ],
        "costBases": [
          "vendor_reported"
        ],
        "coverage": {
          "totalRuns": 3,
          "measuredRuns": 2,
          "totalAttempts": 4,
          "measuredAttempts": 3,
          "complete": false,
          "lowerBound": true
        },
        "models": [
          {
            "model": "gpt-5.6-sol",
            "usageAttempts": 3,
            "measuredAttempts": 3,
            "inputTokens": 36000,
            "outputTokens": 12000,
            "nativeTotals": [
              {
                "unit": "aiCredits",
                "value": 2.5,
                "estimated": false
              }
            ],
            "normalizedTotals": [
              {
                "unit": "usd",
                "value": 0.025,
                "estimated": true
              }
            ],
            "billingModels": [
              "ai_credits"
            ],
            "costBases": [
              "vendor_reported"
            ]
          }
        ],
        "runs": [
          {
            "runId": "run-123",
            "gaggle": "goobers",
            "workflow": "implement",
            "status": "completed",
            "startedAt": "2026-07-18T12:32:56Z",
            "usageAttempts": 3,
            "measuredAttempts": 3,
            "inputTokens": 36000,
            "outputTokens": 12000,
            "nativeTotals": [
              {
                "unit": "aiCredits",
                "value": 2.5,
                "estimated": false
              }
            ],
            "normalizedTotals": [
              {
                "unit": "usd",
                "value": 0.025,
                "estimated": true
              }
            ],
            "billingModels": [
              "ai_credits"
            ],
            "costBases": [
              "vendor_reported"
            ],
            "models": []
          }
        ]
      }
    ],
    "issues": [
      {
        "provider": "github",
        "externalKind": "issue",
        "externalId": "4398",
        "totalRuns": 3,
        "measuredRuns": 2,
        "totalAttempts": 4,
        "measuredAttempts": 3,
        "nativeTotals": [
          {
            "unit": "usd",
            "value": 0.025,
            "estimated": false
          }
        ],
        "normalizedTotals": [
          {
            "unit": "aiCredits",
            "value": 2.5,
            "estimated": true
          }
        ],
        "billingModels": [],
        "costBases": [
          "vendor_reported"
        ],
        "coverage": {
          "totalRuns": 3,
          "measuredRuns": 2,
          "totalAttempts": 4,
          "measuredAttempts": 3,
          "complete": false,
          "lowerBound": true
        },
        "models": [],
        "runs": [
          {
            "runId": "run-124",
            "gaggle": "goobers",
            "workflow": "review",
            "startedAt": "2026-07-18T12:32:56Z",
            "usageAttempts": 2,
            "measuredAttempts": 2,
            "nativeTotals": [
              {
                "unit": "usd",
                "value": 0.025,
                "estimated": false
              }
            ],
            "normalizedTotals": [
              {
                "unit": "aiCredits",
                "value": 2.5,
                "estimated": true
              }
            ],
            "billingModels": [],
            "costBases": [
              "vendor_reported"
            ],
            "models": []
          }
        ]
      }
    ]
  },
  "telemetryStats": {
    "gaggles": [
      {
        "gaggle": "core",
        "totalRuns": 4,
        "completedRuns": 3,
        "failedRuns": 1,
        "infraFailedRuns": 0,
        "otherRuns": 0,
        "successRate": 0.75,
        "avgDurationMs": 120000.5,
        "minDurationMs": 100000,
        "maxDurationMs": 140001
      }
    ],
    "runs": [
      {
        "gaggle": "core",
        "workflow": "implementation",
        "totalRuns": 4,
        "completedRuns": 3,
        "failedRuns": 1,
        "otherRuns": 0,
        "successRate": 0.75,
        "avgDurationMs": 120000.5,
        "minDurationMs": 100000,
        "maxDurationMs": 140001,
        "infraFailedRuns": 0,
        "stuckAbortedRuns": 1
      }
    ],
    "stages": [
      {
        "gaggle": "core",
        "workflow": "implementation",
        "stage": "implement",
        "totalAttempts": 4,
        "succeededAttempts": 3,
        "failedAttempts": 1,
        "successRate": 0.75,
        "avgDurationMs": 120000.5,
        "minDurationMs": 100000,
        "maxDurationMs": 140001,
        "durationSamples": 4,
        "p50DurationMs": 100000,
        "p95DurationMs": 140001,
        "tokenSamples": 4,
        "p50Tokens": 24000,
        "p95Tokens": 48000,
        "costSamples": 4,
        "p50CostAIC": 125,
        "p95CostAIC": 250,
        "retryWasteAttempts": 1,
        "retryWasteDurationMs": 100000,
        "retryWasteTokens": 12000,
        "retryWasteCostAIC": 75,
        "stuckAbortedAttempts": 1
      }
    ],
    "usage": [
      {
        "scope": "workflow",
        "gaggle": "core",
        "workflow": "implementation",
        "totalAttempts": 4,
        "tokenSamples": 4,
        "p50Tokens": 24000,
        "p95Tokens": 48000,
        "premiumRequestSamples": 3,
        "p50CopilotPremiumRequests": 1,
        "p95CopilotPremiumRequests": 2,
        "costSamples": 4,
        "costAIC": 150,
        "p50CostAIC": 125,
        "p95CostAIC": 250,
        "retryWasteAttempts": 1,
        "retryWasteTokens": 12000,
        "retryWasteCostAIC": 75
      }
    ],
    "models": [
      {
        "model": "gpt-5.4",
        "usageSamples": 3,
        "inputTokenSamples": 3,
        "inputTokens": 36000,
        "outputTokenSamples": 3,
        "outputTokens": 12000,
        "premiumRequestSamples": 3,
        "copilotPremiumRequests": 3,
        "costSamples": 3,
        "costAIC": 150
      }
    ],
    "creditAssignment": [
      {
        "gaggle": "core",
        "workflow": "implementation",
        "kind": "gate",
        "stage": "review",
        "identity": "sha256:reviewer",
        "routedRuns": 4,
        "failureRuns": 1,
        "failureShare": 0.25,
        "escalationRuns": 1,
        "retryWasteAttempts": 2,
        "identification": ""
      }
    ],
    "causalCredit": null,
    "curation": {
      "everRecorded": false,
      "runs": 0,
      "reportedRuns": 0,
      "ready": 0,
      "needsHuman": 0,
      "closed": 0,
      "deduped": 0,
      "split": 0,
      "stale": 0,
      "reconciled": 0,
      "milestoned": 0,
      "bounced": 0
    },
    "readyPool": {
      "sampleEverRecorded": false,
      "claimAgeSamples": 0,
      "bounceEverRecorded": false,
      "forwardCurationThroughput": 0,
      "implementationDemand": 0,
      "inFlightClaimSamples": 0,
      "averageInFlightClaimAgeSeconds": 0,
      "oldestInFlightClaimAgeSeconds": 0
    }
  },
  "telemetryErrorSignatures": {
    "items": [
      {
        "code": "stage_failed",
        "errorClass": "unknown",
        "count": 3,
        "lastSeen": "2026-07-18T12:34:56Z",
        "exampleRunId": "run-123",
        "exampleStage": "implement",
        "exampleAttempt": 1
      }
    ]
  },
  "telemetryErrors": {
    "items": [
      {
        "runId": "run-123",
        "workflow": "implementation",
        "stage": "implement",
        "attempt": 1,
        "code": "stage_failed",
        "errorClass": "workflow",
        "message": "stage failed",
        "occurredAt": "2026-07-18T12:34:56Z"
      }
    ],
    "nextCursor": "next-error"
  },
  "configSources": {
    "apiVersion": "v1",
    "schemaVersion": "v1alpha1",
    "items": [
      {
        "id": "source:local",
        "displayName": "Local configuration",
        "kind": "local",
        "revision": "sha256:local-source",
        "capabilities": {
          "read": true,
          "validate": true,
          "directWrite": true,
          "reviewWrite": false
        }
      },
      {
        "id": "source:primary",
        "displayName": "Primary configuration",
        "kind": "git",
        "revision": "sha256:config-source",
        "capabilities": {
          "read": true,
          "validate": true,
          "directWrite": false,
          "reviewWrite": true
        }
      },
      {
        "id": "source:managed",
        "displayName": "Managed configuration",
        "kind": "provider",
        "revision": "managed:42",
        "capabilities": {
          "read": true,
          "validate": false,
          "directWrite": false,
          "reviewWrite": false
        }
      }
    ]
  },
  "configDocuments": {
    "apiVersion": "v1",
    "schemaVersion": "v1alpha1",
    "sourceId": "source:primary",
    "revision": "sha256:config-source",
    "items": [
      {
        "path": "gaggles/core/workflows/implementation.yaml",
        "mediaType": "application/yaml",
        "etag": "sha256:workflow-document",
        "editable": true,
        "definition": {
          "kind": "workflow",
          "name": "implementation",
          "gaggle": "core"
        }
      }
    ]
  },
  "configDocumentRequest": {
    "path": "gaggles/core/workflows/implementation.yaml"
  },
  "configDocument": {
    "apiVersion": "v1",
    "schemaVersion": "v1alpha1",
    "sourceId": "source:primary",
    "revision": "sha256:config-source",
    "document": {
      "path": "gaggles/core/workflows/implementation.yaml",
      "mediaType": "application/yaml",
      "etag": "sha256:workflow-document",
      "editable": true,
      "definition": {
        "kind": "workflow",
        "name": "implementation",
        "gaggle": "core"
      }
    },
    "content": "apiVersion: goobers.dev/v1alpha1\nkind: Workflow\n",
    "diagnostics": []
  },
  "configPreviewRequest": {
    "changeSet": {
      "baseRevision": "sha256:config-source",
      "changes": [
        {
          "path": "gaggles/core/workflows/implementation.yaml",
          "operation": "upsert",
          "baseEtag": "sha256:workflow-document",
          "content": "apiVersion: goobers.dev/v1alpha1\nkind: Workflow\n"
        },
        {
          "path": "gaggles/core/goobers/reviewer.yaml",
          "operation": "upsert",
          "content": "apiVersion: goobers.dev/v1alpha1\nkind: Goober\n"
        }
      ]
    }
  },
  "configPreview": {
    "apiVersion": "v1",
    "schemaVersion": "v1alpha1",
    "sourceId": "source:primary",
    "baseRevision": "sha256:config-source",
    "previewId": "preview:123",
    "eligible": true,
    "diagnostics": [
      {
        "code": "CFG001",
        "severity": "warning",
        "message": "fixture warning",
        "scope": "Workflow/implementation",
        "location": {
          "path": "gaggles/core/workflows/implementation.yaml",
          "line": 2,
          "column": 1
        }
      }
    ],
    "diff": {
      "format": "unified",
      "content": "--- a/gaggles/core/workflows/implementation.yaml\n+++ b/gaggles/core/workflows/implementation.yaml\n",
      "truncated": false
    }
  },
  "configWriteRequest": {
    "previewId": "preview:123",
    "changeSet": {
      "baseRevision": "sha256:config-source",
      "changes": [
        {
          "path": "gaggles/core/workflows/implementation.yaml",
          "operation": "upsert",
          "baseEtag": "sha256:workflow-document",
          "content": "apiVersion: goobers.dev/v1alpha1\nkind: Workflow\n"
        },
        {
          "path": "gaggles/core/goobers/reviewer.yaml",
          "operation": "upsert",
          "content": "apiVersion: goobers.dev/v1alpha1\nkind: Goober\n"
        }
      ]
    },
    "strategy": "review",
    "summary": "Update implementation workflow"
  },
  "configWriteOutcome": {
    "apiVersion": "v1",
    "schemaVersion": "v1alpha1",
    "sourceId": "source:primary",
    "baseRevision": "sha256:config-source",
    "strategy": "review",
    "changedDocuments": [
      "gaggles/core/workflows/implementation.yaml",
      "gaggles/core/goobers/reviewer.yaml"
    ],
    "review": {
      "id": "review:42",
      "url": "https://example.invalid/reviews/42",
      "branch": "goobers/config-preview-123",
      "commit": "0123456789abcdef"
    }
  },
  "configAuthoringError": {
    "error": {
      "code": "config_stale_revision",
      "message": "the configuration source changed; reload and retry"
    }
  },
  "eventInvalidation": {
    "cursor": "fixture:9",
    "models": [
      "instance",
      "run",
      "workflow"
    ],
    "runIds": [
      "run-123"
    ],
    "workflows": [
      {
        "gaggle": "core",
        "name": "implementation"
      }
    ]
  },
  "errorEnvelope": {
    "error": {
      "code": "not_found",
      "message": "requested resource was not found"
    }
  }
} as const satisfies GoWireFixtures;
