// Code generated by go generate ./internal/apicontract; DO NOT EDIT.

import type {
  Health,
  Instance,
  GagglePage,
  GooberPage,
  WorkflowPage,
  WorkflowDetail,
  RunList,
  RunDetail,
  EventList,
  AttemptList,
  TelemetryStatsResult,
  TelemetryErrorSignaturesResult,
  TelemetryErrorsPage,
  ModelInvalidation,
  ApiErrorEnvelope,
} from "./types";

export interface GoWireFixtures {
  health: Health;
  instance: Instance;
  gaggles: GagglePage;
  goobers: GooberPage;
  workflows: WorkflowPage;
  workflowDetail: WorkflowDetail;
  runs: RunList;
  runDetail: RunDetail;
  runEvents: EventList;
  stageAttempts: AttemptList;
  telemetryStats: TelemetryStatsResult;
  telemetryErrorSignatures: TelemetryErrorSignaturesResult;
  telemetryErrors: TelemetryErrorsPage;
  eventInvalidation: ModelInvalidation;
  errorEnvelope: ApiErrorEnvelope;
}

export const goWireFixtures = {
  "health": {
    "apiVersion": "v1",
    "schemaVersion": "v1",
    "ready": true,
    "instance": {
      "name": "fixture",
      "environment": "dev"
    },
    "freshness": {
      "observedAt": "2026-07-18T12:34:56Z",
      "definitionsLoadedAt": "2026-07-18T12:32:56Z",
      "journalUpdatedAt": null
    }
  },
  "instance": {
    "apiVersion": "v1",
    "schemaVersion": "v1",
    "name": "fixture",
    "environment": "dev",
    "ready": true,
    "status": "degraded",
    "concurrency": {
      "activeRuns": 1,
      "maxConcurrentRuns": 4
    },
    "counts": {
      "gaggles": 1,
      "goobers": 1,
      "workflows": 1,
      "activeRuns": 1
    },
    "warnings": [
      {
        "code": "VER001",
        "severity": "warning",
        "scope": "Workflow/implementation",
        "explanation": "fixture warning"
      }
    ]
  },
  "gaggles": {
    "items": [
      {
        "name": "core",
        "displayName": "Core",
        "status": "configured",
        "project": {
          "provider": "github",
          "owner": "Agent-Clubhouse",
          "name": "Goobers",
          "branch": "main",
          "connectionRef": "github"
        },
        "backlog": {
          "provider": "github",
          "project": "Agent-Clubhouse/Goobers",
          "labels": [
            "goobers:ready"
          ],
          "query": "is:issue",
          "connectionRef": "github"
        },
        "gooberCount": 1,
        "workflowCount": 1,
        "activeRunCount": 1,
        "warnings": [
          {
            "code": "VER001",
            "severity": "warning",
            "scope": "Workflow/implementation",
            "explanation": "fixture warning"
          }
        ]
      }
    ],
    "page": {
      "limit": 50,
      "total": 1,
      "hasMore": true,
      "nextCursor": "next-page"
    }
  },
  "goobers": {
    "items": [
      {
        "name": "implementer",
        "displayName": "Implementer",
        "role": "coder",
        "status": "configured",
        "harness": "copilot",
        "skills": [
          "go"
        ],
        "capabilities": [
          "repo:push"
        ],
        "workflows": [
          {
            "gaggle": "core",
            "name": "implementation"
          }
        ],
        "stages": [
          {
            "workflow": {
              "gaggle": "core",
              "name": "implementation"
            },
            "stage": "implement",
            "kind": "agentic"
          }
        ],
        "warnings": [
          {
            "code": "VER001",
            "severity": "warning",
            "scope": "Workflow/implementation",
            "explanation": "fixture warning"
          }
        ]
      }
    ],
    "page": {
      "limit": 50,
      "total": 1,
      "hasMore": true,
      "nextCursor": "next-page"
    }
  },
  "workflows": {
    "items": [
      {
        "identity": {
          "gaggle": "core",
          "name": "implementation"
        },
        "displayName": "Implementation",
        "purpose": "Implement an approved backlog item.",
        "triggers": [
          {
            "type": "backlog-item",
            "selector": {
              "label": "approved"
            }
          },
          {
            "type": "schedule",
            "schedule": "0 * * * *"
          },
          {
            "type": "signal",
            "signal": "backlog-ready"
          },
          {
            "type": "webhook",
            "events": [
              "issues"
            ]
          }
        ],
        "readiness": {
          "maxConcurrentRuns": 1,
          "maxRunsPerHour": 10,
          "maxRunsPerDay": 20,
          "maxChainDepth": 3,
          "maxOpenPRs": 2
        },
        "concurrency": {
          "activeRuns": 1,
          "maxConcurrentRuns": 2
        },
        "owners": [
          {
            "gaggle": "core",
            "name": "implementer"
          }
        ],
        "stageCount": 2,
        "definition": {
          "version": 7,
          "digest": "sha256:workflow"
        },
        "warnings": [
          {
            "code": "VER001",
            "severity": "warning",
            "scope": "Workflow/implementation",
            "explanation": "fixture warning"
          }
        ]
      }
    ],
    "page": {
      "limit": 50,
      "total": 1,
      "hasMore": true,
      "nextCursor": "next-page"
    }
  },
  "workflowDetail": {
    "identity": {
      "gaggle": "core",
      "name": "implementation"
    },
    "displayName": "Implementation",
    "purpose": "Implement an approved backlog item.",
    "triggers": [
      {
        "type": "backlog-item",
        "selector": {
          "label": "approved"
        }
      },
      {
        "type": "schedule",
        "schedule": "0 * * * *"
      },
      {
        "type": "signal",
        "signal": "backlog-ready"
      },
      {
        "type": "webhook",
        "events": [
          "issues"
        ]
      }
    ],
    "readiness": {
      "maxConcurrentRuns": 1,
      "maxRunsPerHour": 10,
      "maxRunsPerDay": 20,
      "maxChainDepth": 3,
      "maxOpenPRs": 2
    },
    "concurrency": {
      "activeRuns": 1,
      "maxConcurrentRuns": 2
    },
    "owners": [
      {
        "gaggle": "core",
        "name": "implementer"
      }
    ],
    "stageCount": 2,
    "definition": {
      "version": 7,
      "digest": "sha256:workflow"
    },
    "warnings": [
      {
        "code": "VER001",
        "severity": "warning",
        "scope": "Workflow/implementation",
        "explanation": "fixture warning"
      }
    ],
    "graph": {
      "name": "implementation",
      "version": 7,
      "digest": "sha256:workflow",
      "start": "implement",
      "nodes": [
        {
          "id": "implement",
          "kind": "agentic",
          "owner": "implementer"
        },
        {
          "id": "review",
          "kind": "gate",
          "evaluator": "agentic"
        }
      ],
      "edges": [
        {
          "source": "implement",
          "target": "review"
        },
        {
          "source": "review",
          "target": "@escalate",
          "outcome": "fail",
          "terminal": "escalate"
        }
      ]
    },
    "stages": [
      {
        "name": "implement",
        "kind": "agentic",
        "goal": "Implement the claimed item.",
        "owner": {
          "gaggle": "core",
          "name": "implementer"
        },
        "evaluator": "",
        "capabilities": [
          "repo:push"
        ]
      },
      {
        "name": "review",
        "kind": "gate",
        "goal": "Review the implementation.",
        "owner": null,
        "evaluator": "agentic",
        "capabilities": [
          "repo:read"
        ]
      }
    ]
  },
  "runs": {
    "runs": [
      {
        "id": "run-123",
        "workflow": "implementation",
        "workflowVersion": 7,
        "workflowDigest": "sha256:workflow",
        "gaggle": "core",
        "trigger": {
          "kind": "item",
          "ref": "673"
        },
        "phase": "escalated",
        "terminal": true,
        "currentStage": "review",
        "startedAt": "2026-07-18T12:32:56Z",
        "finishedAt": "2026-07-18T12:36:56Z",
        "durationMillis": 120000,
        "lastActivityAt": "2026-07-18T12:36:56Z",
        "lastSeq": 9,
        "repassCount": 1,
        "retryCount": 2,
        "policyRetryCount": 1,
        "infraRetryCount": 1
      }
    ],
    "nextCursor": "next-run"
  },
  "runDetail": {
    "id": "run-123",
    "workflow": "implementation",
    "workflowVersion": 7,
    "workflowDigest": "sha256:workflow",
    "gaggle": "core",
    "trigger": {
      "kind": "item",
      "ref": "673"
    },
    "phase": "escalated",
    "terminal": true,
    "currentStage": "review",
    "startedAt": "2026-07-18T12:32:56Z",
    "finishedAt": "2026-07-18T12:36:56Z",
    "durationMillis": 120000,
    "lastActivityAt": "2026-07-18T12:36:56Z",
    "lastSeq": 9,
    "repassCount": 1,
    "retryCount": 2,
    "policyRetryCount": 1,
    "infraRetryCount": 1,
    "graph": {
      "name": "implementation",
      "version": 7,
      "digest": "sha256:workflow",
      "start": "implement",
      "nodes": [
        {
          "id": "implement",
          "kind": "agentic",
          "owner": "implementer"
        },
        {
          "id": "review",
          "kind": "gate",
          "evaluator": "agentic"
        }
      ],
      "edges": [
        {
          "source": "implement",
          "target": "review"
        },
        {
          "source": "review",
          "target": "@escalate",
          "outcome": "fail",
          "terminal": "escalate"
        }
      ]
    },
    "graphStatus": "pinned",
    "escalation": {
      "selector": {
        "kind": "gate",
        "name": "review"
      },
      "selectedBranch": "fail",
      "repassCount": 1,
      "retryCount": 2,
      "terminalReason": "review budget exhausted",
      "causalEventSeq": 9
    }
  },
  "runEvents": {
    "runId": "run-123",
    "events": [
      {
        "schema": "goobers.dev/run-event/v1",
        "seq": 9,
        "type": "stage.finished",
        "branch": 0,
        "time": "2026-07-18T12:36:56Z",
        "knownSchema": true,
        "stage": "implement",
        "attempt": 2,
        "attemptClass": "policy",
        "gate": "review",
        "verdict": "needs-changes",
        "target": "implement",
        "escalated": true,
        "status": "success",
        "outputs": {
          "approved": true,
          "score": 0.98
        },
        "artifacts": [
          {
            "name": "result",
            "digest": "sha256:artifact",
            "size": 42,
            "mediaType": "application/json",
            "stage": "implement",
            "attempt": 2,
            "attemptClass": "policy",
            "recordedSeq": 8
          }
        ],
        "artifact": {
          "name": "result",
          "digest": "sha256:artifact",
          "size": 42,
          "mediaType": "application/json",
          "stage": "implement",
          "attempt": 2,
          "attemptClass": "policy",
          "recordedSeq": 8
        },
        "name": "result",
        "externalRef": {
          "provider": "github",
          "kind": "issue",
          "id": "673",
          "url": "https://github.com/Agent-Clubhouse/Goobers/issues/673"
        },
        "error": {
          "code": "review_failed",
          "message": "review requested changes"
        },
        "redaction": {
          "target": "artifacts/result.json",
          "oldDigest": "sha256:old",
          "newDigest": "sha256:new",
          "reason": "secret remediation"
        },
        "runner": {
          "worker": "local"
        },
        "workflow": "implementation",
        "runId": "run-123",
        "reason": "fixture",
        "raw": {
          "futureField": "preserved"
        }
      }
    ]
  },
  "stageAttempts": {
    "runId": "run-123",
    "stage": "implement",
    "attempts": [
      {
        "number": 2,
        "class": "policy",
        "status": "success",
        "startedSeq": 4,
        "finishedSeq": 8,
        "startedAt": "2026-07-18T12:32:56Z",
        "finishedAt": "2026-07-18T12:36:56Z",
        "durationMillis": 120000,
        "outputs": {
          "summary": "implemented"
        },
        "artifacts": [
          {
            "name": "result",
            "digest": "sha256:artifact",
            "size": 42,
            "mediaType": "application/json",
            "stage": "implement",
            "attempt": 2,
            "attemptClass": "policy",
            "recordedSeq": 8
          }
        ],
        "error": {
          "code": "recovered",
          "message": "completed after retry"
        }
      }
    ]
  },
  "telemetryStats": {
    "gaggles": [
      {
        "gaggle": "core",
        "totalRuns": 4,
        "completedRuns": 3,
        "failedRuns": 1,
        "otherRuns": 0,
        "successRate": 0.75,
        "avgDurationMs": 120000.5,
        "minDurationMs": 100000,
        "maxDurationMs": 140001
      }
    ],
    "runs": [
      {
        "gaggle": "core",
        "workflow": "implementation",
        "totalRuns": 4,
        "completedRuns": 3,
        "failedRuns": 1,
        "otherRuns": 0,
        "successRate": 0.75,
        "avgDurationMs": 120000.5,
        "minDurationMs": 100000,
        "maxDurationMs": 140001
      }
    ],
    "stages": [
      {
        "gaggle": "core",
        "workflow": "implementation",
        "stage": "implement",
        "totalAttempts": 4,
        "succeededAttempts": 3,
        "failedAttempts": 1,
        "successRate": 0.75,
        "avgDurationMs": 120000.5,
        "minDurationMs": 100000,
        "maxDurationMs": 140001,
        "durationSamples": 4,
        "p50DurationMs": 100000,
        "p95DurationMs": 140001,
        "tokenSamples": 4,
        "p50Tokens": 24000,
        "p95Tokens": 48000,
        "costSamples": 4,
        "p50CostUSD": 1.25,
        "p95CostUSD": 2.5,
        "retryWasteAttempts": 1,
        "retryWasteDurationMs": 100000,
        "retryWasteTokens": 12000,
        "retryWasteCostUSD": 0.75
      }
    ],
    "usage": [
      {
        "scope": "workflow",
        "gaggle": "core",
        "workflow": "implementation",
        "totalAttempts": 4,
        "tokenSamples": 4,
        "p50Tokens": 24000,
        "p95Tokens": 48000,
        "premiumRequestSamples": 3,
        "p50CopilotPremiumRequests": 1,
        "p95CopilotPremiumRequests": 2,
        "costSamples": 4,
        "p50CostUSD": 1.25,
        "p95CostUSD": 2.5,
        "retryWasteAttempts": 1,
        "retryWasteTokens": 12000,
        "retryWasteCostUSD": 0.75
      }
    ],
    "models": [
      {
        "model": "gpt-5.4",
        "usageSamples": 3,
        "inputTokenSamples": 3,
        "inputTokens": 36000,
        "outputTokenSamples": 3,
        "outputTokens": 12000,
        "premiumRequestSamples": 3,
        "copilotPremiumRequests": 3,
        "costSamples": 3,
        "costUSD": 1.5
      }
    ]
  },
  "telemetryErrorSignatures": {
    "items": [
      {
        "code": "stage_failed",
        "errorClass": "unknown",
        "count": 3,
        "lastSeen": "2026-07-18T12:34:56Z",
        "exampleRunId": "run-123",
        "exampleStage": "implement",
        "exampleAttempt": 1
      }
    ]
  },
  "telemetryErrors": {
    "items": [
      {
        "runId": "run-123",
        "workflow": "implementation",
        "stage": "implement",
        "attempt": 1,
        "code": "stage_failed",
        "errorClass": "workflow",
        "message": "stage failed",
        "occurredAt": "2026-07-18T12:34:56Z"
      }
    ],
    "nextCursor": "next-error"
  },
  "eventInvalidation": {
    "cursor": "fixture:9",
    "models": [
      "instance",
      "run",
      "workflow"
    ],
    "runIds": [
      "run-123"
    ],
    "workflows": [
      {
        "gaggle": "core",
        "name": "implementation"
      }
    ]
  },
  "errorEnvelope": {
    "error": {
      "code": "not_found",
      "message": "requested resource was not found"
    }
  }
} as const satisfies GoWireFixtures;
