package harness

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	apiv1 "github.com/goobers/goobers/api/v1alpha1"
	"github.com/goobers/goobers/internal/mcpconfig"
	"github.com/goobers/goobers/internal/mcpio"
)

var codexMCPDefaultEnvironment = map[string]bool{
	"HOME": true, "LOGNAME": true, "PATH": true, "SHELL": true, "USER": true,
	"__CF_USER_TEXT_ENCODING": true, "LANG": true, "LC_ALL": true, "TERM": true,
	"TMPDIR": true, "TZ": true, "PATHEXT": true, "COMSPEC": true,
	"SYSTEMROOT": true, "WINDIR": true, "SYSTEMDRIVE": true, "USERNAME": true,
	"USERDOMAIN": true, "USERPROFILE": true, "HOMEDRIVE": true, "HOMEPATH": true,
	"PROGRAMFILES": true, "PROGRAMFILES(X86)": true, "PROGRAMW6432": true,
	"PROGRAMDATA": true, "LOCALAPPDATA": true, "APPDATA": true, "TEMP": true,
	"TMP": true, "POWERSHELL": true, "PWSH": true,
	"CODEX_CA_CERTIFICATE": true, "SSL_CERT_FILE": true, "REQUESTS_CA_BUNDLE": true,
	"CURL_CA_BUNDLE": true, "NODE_EXTRA_CA_CERTS": true, "GIT_SSL_CAINFO": true,
	"CARGO_HTTP_CAINFO": true, "PIP_CERT": true, "BUNDLE_SSL_CA_CERT": true,
	"NPM_CONFIG_CAFILE": true, "CODEX_EXEC_SERVER_NOISE_AUTH_TOKEN": true,
	"NODE_REPL_AUTH_TOKEN": true, "OPENAI_FEDERATION_RULE_ID": true,
	"OPENAI_IDENTITY_TOKEN_FILE": true, "OPENAI_WORKLOAD_IDENTITY_CONTEXT": true,
}

func withAutoGoobersIOCodex(req RunRequest, selfBin string) RunRequest {
	if selfBin == "" || !autoGoobersIOEligible(req) {
		return req
	}
	req.GoobersIORegistered = true
	return req
}

func prepareCodexMCP(ctx context.Context, req RunRequest, configDir, selfBin string, env, reservedEnv []string) ([]string, []string, error) {
	if err := mcpconfig.ValidateForHarness(apiv1.HarnessCodex, req.MCPServers, req.Envelope.Capabilities, req.Tools); err != nil {
		return nil, nil, fmt.Errorf("harness: codex: invalid MCP configuration: %w", err)
	}

	var config strings.Builder
	config.WriteString("# Generated by Goobers for one Codex invocation.\n")
	if req.GoobersIORegistered {
		for _, server := range req.MCPServers {
			if server.Name == goobersIOServerName {
				return nil, nil, fmt.Errorf("harness: codex: MCP server name %q is reserved for automatic goobers-io registration", server.Name)
			}
		}
		artifactFile, _ := req.Envelope.Inputs[InputArtifactFile].(string)
		artifactManifestFile, _ := req.Envelope.Inputs[InputArtifactManifestFile].(string)
		cfg := mcpio.Config{
			Workspace:            req.Workspace,
			ArtifactFile:         artifactFile,
			ArtifactManifestFile: artifactManifestFile,
			ReceiptFile:          goobersIOReceiptFile(),
			Inputs:               req.ContextPaths,
			RunID:                req.Envelope.RunID,
			WorkflowID:           req.Envelope.WorkflowID,
			TaskID:               req.Envelope.TaskID,
			Gaggle:               req.Envelope.Gaggle,
		}
		configRel := filepath.Join(filepath.FromSlash(goobersIORuntimeSubdir), mcpio.ConfigFileName)
		configPath, err := mcpio.WriteConfig(req.Workspace, configRel, cfg)
		if err != nil {
			return nil, nil, fmt.Errorf("harness: codex: write goobers-io config: %w", err)
		}
		if err := mcpio.ResetInputInspectionReceipts(req.Workspace, cfg.ReceiptFile); err != nil {
			return nil, nil, fmt.Errorf("harness: codex: reset goobers-io input inspection receipts: %w", err)
		}
		writeCodexStdioServer(&config, goobersIOServerName, selfBin, []string{"mcp-io", "--config", configPath}, nil, nil)
	}

	localEnvOwners := map[string]string{}
	reserved := make(map[string]bool, len(reservedEnv))
	for _, name := range reservedEnv {
		reserved[strings.ToUpper(name)] = true
	}
	var secretEnvNames []string
	for serverIndex, server := range req.MCPServers {
		var envNames []string
		var headerEnv = map[string]string{}
		for refIndex, ref := range server.CredentialRefs {
			if req.Credentials == nil {
				return nil, nil, fmt.Errorf("harness: codex: MCP server %q requires credentials but none were materialized", server.Name)
			}
			key := mcpconfig.CredentialKey(ref)
			token, err := req.Credentials.Token(ctx, key)
			if err != nil {
				return nil, nil, fmt.Errorf("harness: codex: resolve MCP server %q credential %q: %w", server.Name, key, err)
			}
			if ref.Env != "" {
				normalized := strings.ToUpper(ref.Env)
				if reserved[normalized] || codexMCPDefaultEnvironment[normalized] || strings.HasPrefix(normalized, "GOOBERS_MCP_CREDENTIAL_") {
					return nil, nil, fmt.Errorf("harness: codex: MCP environment variable %q is reserved by the adapter", ref.Env)
				}
				if owner, exists := localEnvOwners[normalized]; exists && owner != key {
					return nil, nil, fmt.Errorf("harness: codex: MCP environment variable %q is bound to both %q and %q", ref.Env, owner, key)
				}
				localEnvOwners[normalized] = key
				env = overrideEnv(env, ref.Env, token)
				envNames = append(envNames, ref.Env)
				secretEnvNames = append(secretEnvNames, ref.Env)
				continue
			}
			envName := fmt.Sprintf("GOOBERS_MCP_CREDENTIAL_%d_%d", serverIndex, refIndex)
			if reserved[strings.ToUpper(envName)] {
				return nil, nil, fmt.Errorf("harness: codex: generated MCP environment variable %q is reserved by the adapter", envName)
			}
			switch ref.Scheme {
			case apiv1.MCPHeaderSchemeBearer:
				token = "Bearer " + token
			case apiv1.MCPHeaderSchemeBasic:
				token = "Basic " + token
			}
			env = overrideEnv(env, envName, token)
			secretEnvNames = append(secretEnvNames, envName)
			headerEnv[ref.Header] = envName
		}
		if server.Command != "" {
			writeCodexStdioServer(&config, server.Name, server.Command, server.Args, envNames, req.Tools)
		} else {
			writeCodexHTTPServer(&config, server.Name, server.URL, headerEnv, req.Tools)
		}
	}
	if err := os.WriteFile(filepath.Join(configDir, "config.toml"), []byte(config.String()), 0o600); err != nil {
		return nil, nil, fmt.Errorf("harness: codex: write scoped MCP config: %w", err)
	}
	return env, secretEnvNames, nil
}

func writeCodexStdioServer(config *strings.Builder, name, command string, args, envNames, tools []string) {
	fmt.Fprintf(config, "\n[mcp_servers.%s]\n", tomlQuote(name))
	fmt.Fprintf(config, "command = %s\n", tomlQuote(command))
	writeCodexStringArray(config, "args", args)
	writeCodexStringArray(config, "env_vars", envNames)
	config.WriteString("enabled = true\nrequired = true\n")
	writeCodexStringArray(config, "enabled_tools", tools)
}

func writeCodexHTTPServer(config *strings.Builder, name, url string, headers map[string]string, tools []string) {
	fmt.Fprintf(config, "\n[mcp_servers.%s]\n", tomlQuote(name))
	fmt.Fprintf(config, "url = %s\n", tomlQuote(url))
	if len(headers) > 0 {
		names := make([]string, 0, len(headers))
		for name := range headers {
			names = append(names, name)
		}
		sort.Strings(names)
		config.WriteString("env_http_headers = { ")
		for i, name := range names {
			if i > 0 {
				config.WriteString(", ")
			}
			fmt.Fprintf(config, "%s = %s", tomlQuote(name), tomlQuote(headers[name]))
		}
		config.WriteString(" }\n")
	}
	config.WriteString("enabled = true\nrequired = true\n")
	writeCodexStringArray(config, "enabled_tools", tools)
}

func writeCodexStringArray(config *strings.Builder, name string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(config, "%s = [", name)
	for i, value := range values {
		if i > 0 {
			config.WriteString(", ")
		}
		config.WriteString(tomlQuote(value))
	}
	config.WriteString("]\n")
}
