package harness

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	apiv1 "github.com/goobers/goobers/api/v1alpha1"
	"github.com/goobers/goobers/internal/mcpio"
)

var codexMCPDefaultEnvironment = map[string]bool{
	"HOME": true, "LOGNAME": true, "PATH": true, "SHELL": true, "USER": true,
	"__CF_USER_TEXT_ENCODING": true, "LANG": true, "LC_ALL": true, "TERM": true,
	"TMPDIR": true, "TZ": true, "PATHEXT": true, "COMSPEC": true,
	"SYSTEMROOT": true, "WINDIR": true, "SYSTEMDRIVE": true, "USERNAME": true,
	"USERDOMAIN": true, "USERPROFILE": true, "HOMEDRIVE": true, "HOMEPATH": true,
	"PROGRAMFILES": true, "PROGRAMFILES(X86)": true, "PROGRAMW6432": true,
	"PROGRAMDATA": true, "LOCALAPPDATA": true, "APPDATA": true, "TEMP": true,
	"TMP": true, "POWERSHELL": true, "PWSH": true,
	"CODEX_CA_CERTIFICATE": true, "SSL_CERT_FILE": true, "REQUESTS_CA_BUNDLE": true,
	"CURL_CA_BUNDLE": true, "NODE_EXTRA_CA_CERTS": true, "GIT_SSL_CAINFO": true,
	"CARGO_HTTP_CAINFO": true, "PIP_CERT": true, "BUNDLE_SSL_CA_CERT": true,
	"NPM_CONFIG_CAFILE": true, "CODEX_EXEC_SERVER_NOISE_AUTH_TOKEN": true,
	"NODE_REPL_AUTH_TOKEN": true, "OPENAI_FEDERATION_RULE_ID": true,
	"OPENAI_IDENTITY_TOKEN_FILE": true, "OPENAI_WORKLOAD_IDENTITY_CONTEXT": true,
}

func withAutoGoobersIOCodex(req RunRequest, selfBin string) RunRequest {
	if selfBin == "" || !autoGoobersIOEligible(req) {
		return req
	}
	req.GoobersIORegistered = true
	return req
}

func prepareCodexMCP(ctx context.Context, req RunRequest, configDir, selfBin string, env, reservedEnv []string, writeConfig bool) ([]string, []string, []string, error) {
	reservedServerName := ""
	if req.GoobersIORegistered {
		reservedServerName = goobersIOServerName
	}
	servers, assignments, err := materializeDeclaredMCP(ctx, "codex", req, mcpMaterializeOptions{
		harness:              apiv1.HarnessCodex,
		localEnvRefs:         true,
		headerValuesInEnv:    true,
		reservedEnv:          reservedEnv,
		defaultReservedLocal: codexMCPDefaultEnvironment,
		reservedServerName:   reservedServerName,
	})
	if err != nil {
		return nil, nil, nil, err
	}

	var config strings.Builder
	config.WriteString("# Generated by Goobers for one Codex invocation.\n")
	var overrides []string
	if req.GoobersIORegistered {
		artifactFile, _ := req.Envelope.Inputs[InputArtifactFile].(string)
		artifactManifestFile, _ := req.Envelope.Inputs[InputArtifactManifestFile].(string)
		cfg := mcpio.Config{
			Workspace:            req.Workspace,
			ArtifactFile:         artifactFile,
			ArtifactManifestFile: artifactManifestFile,
			ReceiptFile:          goobersIOReceiptFile(),
			Inputs:               req.ContextPaths,
			RunID:                req.Envelope.RunID,
			WorkflowID:           req.Envelope.WorkflowID,
			TaskID:               req.Envelope.TaskID,
			Gaggle:               req.Envelope.Gaggle,
		}
		configRel := filepath.Join(filepath.FromSlash(goobersIORuntimeSubdir), mcpio.ConfigFileName)
		configPath, err := mcpio.WriteConfig(req.Workspace, configRel, cfg)
		if err != nil {
			return nil, nil, nil, fmt.Errorf("harness: codex: write goobers-io config: %w", err)
		}
		if err := mcpio.ResetInputInspectionReceipts(req.Workspace, cfg.ReceiptFile); err != nil {
			return nil, nil, nil, fmt.Errorf("harness: codex: reset goobers-io input inspection receipts: %w", err)
		}
		writeCodexStdioServer(&config, goobersIOServerName, selfBin, []string{"mcp-io", "--config", configPath}, nil, nil)
		overrides = appendCodexStdioOverrides(overrides, goobersIOServerName, selfBin, []string{"mcp-io", "--config", configPath}, nil, nil)
	}

	var secretEnvNames []string
	for _, assignment := range assignments {
		env = overrideEnv(env, assignment.Name, assignment.Value)
		secretEnvNames = append(secretEnvNames, assignment.Name)
	}
	for _, server := range servers {
		if server.Command != "" {
			writeCodexStdioServer(&config, server.Name, server.Command, server.Args, server.EnvNames, req.Tools)
			overrides = appendCodexStdioOverrides(overrides, server.Name, server.Command, server.Args, server.EnvNames, req.Tools)
		} else {
			writeCodexHTTPServer(&config, server.Name, server.URL, server.Headers, req.Tools)
			overrides = appendCodexHTTPOverrides(overrides, server.Name, server.URL, server.Headers, req.Tools)
		}
	}
	if writeConfig {
		if err := os.WriteFile(filepath.Join(configDir, "config.toml"), []byte(config.String()), 0o600); err != nil {
			return nil, nil, nil, fmt.Errorf("harness: codex: write scoped MCP config: %w", err)
		}
	}
	return env, secretEnvNames, overrides, nil
}

func appendCodexStdioOverrides(overrides []string, name, command string, args, envNames, tools []string) []string {
	prefix := `mcp_servers.` + codexOverrideServerName(name)
	overrides = append(overrides, prefix+`.command=`+tomlQuote(command), prefix+`.enabled=true`, prefix+`.required=true`)
	if len(args) > 0 {
		overrides = append(overrides, prefix+`.args=`+tomlStringArray(args))
	}
	if len(envNames) > 0 {
		overrides = append(overrides, prefix+`.env_vars=`+tomlStringArray(envNames))
	}
	if len(tools) > 0 {
		overrides = append(overrides, prefix+`.enabled_tools=`+tomlStringArray(tools))
	}
	return overrides
}

func codexOverrideServerName(name string) string {
	// Codex accepts the auto-wired server's hyphenated name as a bare override
	// segment. Quoting it here leaves the quote characters in the resolved MCP
	// server name on current Codex builds, which then reject the server before
	// session startup.
	if name == goobersIOServerName {
		return name
	}
	return tomlQuote(name)
}

func appendCodexHTTPOverrides(overrides []string, name, url string, headers map[string]string, tools []string) []string {
	prefix := `mcp_servers.` + tomlQuote(name)
	overrides = append(overrides, prefix+`.url=`+tomlQuote(url), prefix+`.enabled=true`, prefix+`.required=true`)
	if len(headers) > 0 {
		overrides = append(overrides, prefix+`.env_http_headers=`+tomlStringMap(headers))
	}
	if len(tools) > 0 {
		overrides = append(overrides, prefix+`.enabled_tools=`+tomlStringArray(tools))
	}
	return overrides
}

func tomlStringArray(values []string) string {
	var out strings.Builder
	out.WriteByte('[')
	for i, value := range values {
		if i > 0 {
			out.WriteString(", ")
		}
		out.WriteString(tomlQuote(value))
	}
	out.WriteByte(']')
	return out.String()
}

func writeCodexStdioServer(config *strings.Builder, name, command string, args, envNames, tools []string) {
	fmt.Fprintf(config, "\n[mcp_servers.%s]\n", tomlQuote(name))
	fmt.Fprintf(config, "command = %s\n", tomlQuote(command))
	writeCodexStringArray(config, "args", args)
	writeCodexStringArray(config, "env_vars", envNames)
	config.WriteString("enabled = true\nrequired = true\n")
	writeCodexStringArray(config, "enabled_tools", tools)
}

func writeCodexHTTPServer(config *strings.Builder, name, url string, headers map[string]string, tools []string) {
	fmt.Fprintf(config, "\n[mcp_servers.%s]\n", tomlQuote(name))
	fmt.Fprintf(config, "url = %s\n", tomlQuote(url))
	if len(headers) > 0 {
		names := make([]string, 0, len(headers))
		for name := range headers {
			names = append(names, name)
		}
		sort.Strings(names)
		config.WriteString("env_http_headers = { ")
		for i, name := range names {
			if i > 0 {
				config.WriteString(", ")
			}
			fmt.Fprintf(config, "%s = %s", tomlQuote(name), tomlQuote(headers[name]))
		}
		config.WriteString(" }\n")
	}
	config.WriteString("enabled = true\nrequired = true\n")
	writeCodexStringArray(config, "enabled_tools", tools)
}

func writeCodexStringArray(config *strings.Builder, name string, values []string) {
	if len(values) == 0 {
		return
	}
	fmt.Fprintf(config, "%s = [", name)
	for i, value := range values {
		if i > 0 {
			config.WriteString(", ")
		}
		config.WriteString(tomlQuote(value))
	}
	config.WriteString("]\n")
}
