package harness

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/goobers/goobers/internal/mcpio"
)

func TestGoobersIOAdapterRegistrationContracts(t *testing.T) {
	const selfBin = "/usr/local/bin/goobers"
	const toolsJSON = `["get_run_info","publish_output","list_inputs","read_input","grep_input"]`

	tests := []struct {
		name   string
		render func(t *testing.T, req RunRequest) string
		want   func(configPath string) string
	}{
		{
			name: "copilot file JSON",
			render: func(t *testing.T, req RunRequest) string {
				t.Helper()
				registrationPath, err := goobersIOAdditionalMCPConfigArg(req, selfBin)
				if err != nil {
					t.Fatal(err)
				}
				data, err := os.ReadFile(registrationPath)
				if err != nil {
					t.Fatal(err)
				}
				return string(data)
			},
			want: func(configPath string) string {
				return fmt.Sprintf(
					`{"mcpServers":{"goobers-io":{"type":"local","command":%s,"args":["mcp-io","--config",%s],"tools":%s}}}`,
					strconv.Quote(selfBin), strconv.Quote(configPath), toolsJSON,
				)
			},
		},
		{
			name: "claude inline JSON",
			render: func(t *testing.T, req RunRequest) string {
				t.Helper()
				arg, err := goobersIOClaudeMCPConfigArg(req, selfBin)
				if err != nil {
					t.Fatal(err)
				}
				return arg
			},
			want: func(configPath string) string {
				return fmt.Sprintf(
					`{"mcpServers":{"goobers-io":{"type":"stdio","command":%s,"args":["mcp-io","--config",%s]}}}`,
					strconv.Quote(selfBin), strconv.Quote(configPath),
				)
			},
		},
		{
			name: "codex TOML and overrides",
			render: func(t *testing.T, req RunRequest) string {
				t.Helper()
				req.GoobersIORegistered = true
				configDir := t.TempDir()
				_, _, overrides, err := prepareCodexMCP(context.Background(), req, configDir, selfBin, nil, nil, true)
				if err != nil {
					t.Fatal(err)
				}
				data, err := os.ReadFile(filepath.Join(configDir, "config.toml"))
				if err != nil {
					t.Fatal(err)
				}
				return string(data) + "OVERRIDES\n" + strings.Join(overrides, "\n")
			},
			want: func(configPath string) string {
				args := []string{"mcp-io", "--config", configPath}
				return "# Generated by Goobers for one Codex invocation.\n" +
					"\n[mcp_servers.\"goobers-io\"]\n" +
					"command = " + tomlQuote(selfBin) + "\n" +
					"args = " + tomlStringArray(args) + "\n" +
					"enabled = true\nrequired = true\n" +
					"OVERRIDES\n" +
					strings.Join(appendCodexStdioOverrides(nil, goobersIOServerName, selfBin, args, nil, nil), "\n")
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			workspace := t.TempDir()
			receiptPath := filepath.Join(workspace, goobersIOReceiptFile())
			if err := os.MkdirAll(filepath.Dir(receiptPath), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(receiptPath, []byte(`{"tool":"list_inputs","success":true}`+"\n"), 0o600); err != nil {
				t.Fatal(err)
			}
			req := RunRequest{
				Envelope:  testEnvelope(workspace),
				Workspace: workspace,
				ContextPaths: map[string]string{
					"review.artifact[0]": ".goobers/context/00-review.artifact_0_",
				},
			}
			req.Envelope.Inputs = map[string]interface{}{
				InputArtifactFile:         "result.json",
				InputArtifactManifestFile: "manifest.json",
			}

			got := tc.render(t, req)
			resolvedWorkspace, err := filepath.EvalSymlinks(workspace)
			if err != nil {
				t.Fatal(err)
			}
			configPath := filepath.Join(resolvedWorkspace, filepath.FromSlash(goobersIORuntimeSubdir), mcpio.ConfigFileName)
			if want := tc.want(configPath); got != want {
				t.Fatalf("registration changed\n got: %s\nwant: %s", got, want)
			}
			if _, err := os.Stat(receiptPath); !os.IsNotExist(err) {
				t.Fatalf("stale receipt log was not reset: %v", err)
			}
			cfg, err := mcpio.LoadConfig(configPath)
			if err != nil {
				t.Fatal(err)
			}
			if cfg.ArtifactFile != "result.json" || cfg.ArtifactManifestFile != "manifest.json" {
				t.Fatalf("runtime output paths changed: %+v", cfg)
			}
			if cfg.Inputs["review.artifact[0]"] != ".goobers/context/00-review.artifact_0_" {
				t.Fatalf("runtime inputs changed: %v", cfg.Inputs)
			}
		})
	}
}
