apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../goobers-system
  - mirror-pvc.yaml

patches:
  - path: daemon.yaml
  - path: worker-linux.yaml
  - path: worker-windows.yaml
