package apicontract

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	apiv1 "github.com/goobers/goobers/api/v1alpha1"
	"github.com/goobers/goobers/api/validate"
	"github.com/goobers/goobers/internal/journal"
	"github.com/goobers/goobers/internal/readservice"
	"github.com/goobers/goobers/internal/workflow"
)

type wireFixtures struct {
	Health                   readservice.Health                         `json:"health"`
	Instance                 readservice.Instance                       `json:"instance"`
	Gaggles                  readservice.GagglePage                     `json:"gaggles"`
	Goobers                  readservice.GooberPage                     `json:"goobers"`
	Workflows                readservice.WorkflowPage                   `json:"workflows"`
	WorkflowDetail           readservice.WorkflowDetail                 `json:"workflowDetail"`
	Runs                     readservice.RunList                        `json:"runs"`
	RunDetail                readservice.RunDetail                      `json:"runDetail"`
	RunEvents                readservice.EventList                      `json:"runEvents"`
	StageAttempts            readservice.AttemptList                    `json:"stageAttempts"`
	TelemetryStats           readservice.TelemetryStatsResult           `json:"telemetryStats"`
	TelemetryErrorSignatures readservice.TelemetryErrorSignaturesResult `json:"telemetryErrorSignatures"`
	TelemetryErrors          readservice.TelemetryErrorsPage            `json:"telemetryErrors"`
	EventInvalidation        Invalidation                               `json:"eventInvalidation"`
	ErrorEnvelope            ErrorEnvelope                              `json:"errorEnvelope"`
}

var wireFixtureTypes = []struct {
	name       string
	scriptType string
}{
	{name: "health", scriptType: "Health"},
	{name: "instance", scriptType: "Instance"},
	{name: "gaggles", scriptType: "GagglePage"},
	{name: "goobers", scriptType: "GooberPage"},
	{name: "workflows", scriptType: "WorkflowPage"},
	{name: "workflowDetail", scriptType: "WorkflowDetail"},
	{name: "runs", scriptType: "RunList"},
	{name: "runDetail", scriptType: "RunDetail"},
	{name: "runEvents", scriptType: "EventList"},
	{name: "stageAttempts", scriptType: "AttemptList"},
	{name: "telemetryStats", scriptType: "TelemetryStatsResult"},
	{name: "telemetryErrorSignatures", scriptType: "TelemetryErrorSignaturesResult"},
	{name: "telemetryErrors", scriptType: "TelemetryErrorsPage"},
	{name: "eventInvalidation", scriptType: "ModelInvalidation"},
	{name: "errorEnvelope", scriptType: "ApiErrorEnvelope"},
}

// TypeScriptWireFixtures renders representative Go response values that the
// portal type-checks against its daemon client models.
func TypeScriptWireFixtures() ([]byte, error) {
	fixtures, err := json.MarshalIndent(newWireFixtures(), "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal wire fixtures: %w", err)
	}

	var output strings.Builder
	output.WriteString("// Code generated by go generate ./internal/apicontract; DO NOT EDIT.\n\n")
	output.WriteString("import type {\n")
	for _, fixtureType := range wireFixtureTypes {
		output.WriteString("  ")
		output.WriteString(fixtureType.scriptType)
		output.WriteString(",\n")
	}
	output.WriteString("} from \"./types\";\n\n")
	output.WriteString("export interface GoWireFixtures {\n")
	for _, fixtureType := range wireFixtureTypes {
		output.WriteString("  ")
		output.WriteString(fixtureType.name)
		output.WriteString(": ")
		output.WriteString(fixtureType.scriptType)
		output.WriteString(";\n")
	}
	output.WriteString("}\n\n")
	output.WriteString("export const goWireFixtures = ")
	output.Write(fixtures)
	output.WriteString(" as const satisfies GoWireFixtures;\n")
	return []byte(output.String()), nil
}

func newWireFixtures() wireFixtures {
	timestamp := time.Date(2026, time.July, 18, 12, 34, 56, 0, time.UTC)
	finishedAt := timestamp.Add(2 * time.Minute)
	startedAt := timestamp.Add(-2 * time.Minute)
	successRate := 0.75
	averageDuration := 120000.5
	minDuration := int64(100000)
	maxDuration := int64(140001)
	p50Tokens := int64(24000)
	p95Tokens := int64(48000)
	p50CostUSD := 1.25
	p95CostUSD := 2.5
	retryWasteDuration := int64(100000)
	retryWasteTokens := int64(12000)
	retryWasteCostUSD := 0.75
	modelInputTokens := int64(36000)
	modelOutputTokens := int64(12000)
	modelPremiumRequests := 3.0
	modelCostUSD := 1.5
	warning := validate.CodedWarning{
		Code:        validate.WarningDeprecatedFeature,
		Severity:    validate.Warning,
		Scope:       "Workflow/implementation",
		Explanation: "fixture warning",
	}
	page := readservice.PageInfo{
		Limit:      50,
		Total:      1,
		HasMore:    true,
		NextCursor: "next-page",
	}
	graph := workflow.Graph{
		Name:    "implementation",
		Version: 7,
		Digest:  "sha256:workflow",
		Start:   "implement",
		Nodes: []workflow.GraphNode{
			{ID: "implement", Kind: workflow.GraphNodeAgentic, Owner: "implementer"},
			{ID: "review", Kind: workflow.GraphNodeGate, Evaluator: apiv1.EvaluatorAgentic},
		},
		Edges: []workflow.GraphEdge{
			{Source: "implement", Target: "review"},
			{
				Source:   "review",
				Target:   workflow.TargetEscalate,
				Outcome:  "fail",
				Terminal: workflow.GraphTerminalEscalate,
			},
		},
	}
	workflowSummary := readservice.WorkflowSummary{
		Identity:    readservice.WorkflowReference{Gaggle: "core", Name: "implementation"},
		DisplayName: "Implementation",
		Purpose:     "Implement an approved backlog item.",
		Triggers: []apiv1.Trigger{
			{Type: apiv1.TriggerBacklogItem, Selector: map[string]string{"label": "approved"}},
			{Type: apiv1.TriggerSchedule, Schedule: "0 * * * *"},
			{Type: apiv1.TriggerSignal, Signal: "backlog-ready"},
			{Type: apiv1.TriggerWebhook, Events: []string{"issues"}},
		},
		Readiness: apiv1.ReadinessConditions{
			MaxConcurrentRuns: 1,
			MaxRunsPerHour:    10,
			MaxRunsPerDay:     20,
			MaxChainDepth:     3,
			MaxOpenPRs:        2,
		},
		Concurrency: readservice.WorkflowConcurrency{
			ActiveRuns:        1,
			MaxConcurrentRuns: 2,
		},
		Owners:     []readservice.GooberReference{{Gaggle: "core", Name: "implementer"}},
		StageCount: 2,
		Definition: readservice.WorkflowDefinition{
			Version: 7,
			Digest:  "sha256:workflow",
		},
		Warnings: []validate.CodedWarning{warning},
	}
	runSummary := readservice.RunSummary{
		ID:              "run-123",
		Workflow:        "implementation",
		WorkflowVersion: 7,
		WorkflowDigest:  "sha256:workflow",
		Gaggle:          "core",
		Trigger: journal.Trigger{
			Kind: journal.TriggerItem,
			Ref:  "673",
		},
		Phase:            journal.PhaseEscalated,
		Terminal:         true,
		CurrentStage:     "review",
		StartedAt:        startedAt,
		FinishedAt:       &finishedAt,
		DurationMillis:   120000,
		LastActivityAt:   finishedAt,
		LastSeq:          9,
		RepassCount:      1,
		RetryCount:       2,
		PolicyRetryCount: 1,
		InfraRetryCount:  1,
	}
	artifact := readservice.ArtifactMetadata{
		Name:         "result",
		Digest:       "sha256:artifact",
		Size:         42,
		MediaType:    "application/json",
		Stage:        "implement",
		Attempt:      2,
		AttemptClass: string(journal.AttemptPolicy),
		RecordedSeq:  8,
	}

	return wireFixtures{
		Health: readservice.Health{
			APIVersion:    readservice.APIVersion,
			SchemaVersion: readservice.SchemaVersion,
			Ready:         true,
			Instance: readservice.InstanceIdentity{
				Name:        "fixture",
				Environment: apiv1.EnvironmentDev,
			},
			Freshness: readservice.Freshness{
				ObservedAt:          timestamp,
				DefinitionsLoadedAt: startedAt,
				JournalUpdatedAt:    nil,
			},
		},
		Instance: readservice.Instance{
			APIVersion:    readservice.APIVersion,
			SchemaVersion: readservice.SchemaVersion,
			Name:          "fixture",
			Environment:   apiv1.EnvironmentDev,
			Ready:         true,
			Status:        readservice.InstanceStatusDegraded,
			Concurrency: readservice.Concurrency{
				ActiveRuns:        1,
				MaxConcurrentRuns: 4,
			},
			Counts: readservice.InventoryCounts{
				Gaggles:    1,
				Goobers:    1,
				Workflows:  1,
				ActiveRuns: 1,
			},
			Warnings: []validate.CodedWarning{warning},
		},
		Gaggles: readservice.GagglePage{
			Items: []readservice.Gaggle{{
				Name:        "core",
				DisplayName: "Core",
				Status:      readservice.DefinitionStatusConfigured,
				Project: apiv1.RepoRef{
					Provider:      apiv1.ProviderGitHub,
					Owner:         "Agent-Clubhouse",
					Name:          "Goobers",
					Branch:        "main",
					ConnectionRef: "github",
				},
				Backlog: apiv1.BacklogRef{
					Provider:      apiv1.ProviderGitHub,
					Project:       "Agent-Clubhouse/Goobers",
					Labels:        []string{"goobers:ready"},
					Query:         "is:issue",
					ConnectionRef: "github",
				},
				GooberCount:    1,
				WorkflowCount:  1,
				ActiveRunCount: 1,
				Warnings:       []validate.CodedWarning{warning},
			}},
			Page: page,
		},
		Goobers: readservice.GooberPage{
			Items: []readservice.Goober{{
				Name:         "implementer",
				DisplayName:  "Implementer",
				Role:         "coder",
				Status:       readservice.DefinitionStatusConfigured,
				Harness:      apiv1.HarnessCopilot,
				Skills:       []string{"go"},
				Capabilities: []string{"repo:push"},
				Workflows:    []readservice.WorkflowReference{{Gaggle: "core", Name: "implementation"}},
				Stages: []readservice.StageOwnership{{
					Workflow: readservice.WorkflowReference{Gaggle: "core", Name: "implementation"},
					Stage:    "implement",
					Kind:     workflow.GraphNodeAgentic,
				}},
				Warnings: []validate.CodedWarning{warning},
			}},
			Page: page,
		},
		Workflows: readservice.WorkflowPage{
			Items: []readservice.WorkflowSummary{workflowSummary},
			Page:  page,
		},
		WorkflowDetail: readservice.WorkflowDetail{
			WorkflowSummary: workflowSummary,
			Graph:           graph,
			Stages: []readservice.StageDefinition{
				{
					Name:         "implement",
					Kind:         workflow.GraphNodeAgentic,
					Goal:         "Implement the claimed item.",
					Owner:        &readservice.GooberReference{Gaggle: "core", Name: "implementer"},
					Evaluator:    "",
					Capabilities: []string{"repo:push"},
				},
				{
					Name:         "review",
					Kind:         workflow.GraphNodeGate,
					Goal:         "Review the implementation.",
					Owner:        nil,
					Evaluator:    apiv1.EvaluatorAgentic,
					Capabilities: []string{"repo:read"},
				},
			},
		},
		Runs: readservice.RunList{
			Runs:       []readservice.RunSummary{runSummary},
			NextCursor: "next-run",
		},
		RunDetail: readservice.RunDetail{
			RunSummary:  runSummary,
			Graph:       &graph,
			GraphStatus: "pinned",
			Escalation: &readservice.EscalationCause{
				Selector:       readservice.EscalationSelector{Kind: "gate", Name: "review"},
				SelectedBranch: "fail",
				RepassCount:    1,
				RetryCount:     2,
				TerminalReason: "review budget exhausted",
				CausalEventSeq: 9,
			},
		},
		RunEvents: readservice.EventList{
			RunID: "run-123",
			Events: []readservice.RunEvent{{
				Schema:       "goobers.dev/run-event/v1",
				Seq:          9,
				Type:         journal.EventStageFinished,
				Branch:       0,
				Time:         finishedAt,
				KnownSchema:  true,
				Stage:        "implement",
				Attempt:      2,
				AttemptClass: string(journal.AttemptPolicy),
				Gate:         "review",
				Verdict:      "needs-changes",
				Target:       "implement",
				Escalated:    true,
				Status:       string(apiv1.ResultSuccess),
				Outputs:      map[string]any{"approved": true, "score": 0.98},
				Artifacts:    []readservice.ArtifactMetadata{artifact},
				Artifact:     &artifact,
				Name:         "result",
				ExternalRef: &journal.ExternalRef{
					Provider: "github",
					Kind:     "issue",
					ID:       "673",
					URL:      "https://github.com/Agent-Clubhouse/Goobers/issues/673",
				},
				Error: &journal.ErrorDetail{
					Code:    "review_failed",
					Message: "review requested changes",
				},
				Redaction: &journal.RedactionInfo{
					Target:    "artifacts/result.json",
					OldDigest: "sha256:old",
					NewDigest: "sha256:new",
					Reason:    "secret remediation",
				},
				Runner:   map[string]any{"worker": "local"},
				Workflow: "implementation",
				RunID:    "run-123",
				Reason:   "fixture",
				Raw:      json.RawMessage(`{"futureField":"preserved"}`),
			}},
		},
		StageAttempts: readservice.AttemptList{
			RunID: "run-123",
			Stage: "implement",
			Attempts: []readservice.StageAttempt{{
				Number:         2,
				Class:          string(journal.AttemptPolicy),
				Status:         string(apiv1.ResultSuccess),
				StartedSeq:     4,
				FinishedSeq:    8,
				StartedAt:      &startedAt,
				FinishedAt:     &finishedAt,
				DurationMillis: 120000,
				Outputs:        map[string]any{"summary": "implemented"},
				Artifacts:      []readservice.ArtifactMetadata{artifact},
				Error: &journal.ErrorDetail{
					Code:    "recovered",
					Message: "completed after retry",
				},
			}},
		},
		TelemetryStats: readservice.TelemetryStatsResult{
			Gaggles: []readservice.TelemetryGaggleStats{{
				Gaggle:        "core",
				TotalRuns:     4,
				CompletedRuns: 3,
				FailedRuns:    1,
				OtherRuns:     0,
				SuccessRate:   &successRate,
				AvgDurationMs: &averageDuration,
				MinDurationMs: &minDuration,
				MaxDurationMs: &maxDuration,
			}},
			Runs: []readservice.TelemetryRunStats{{
				Gaggle:        "core",
				Workflow:      "implementation",
				TotalRuns:     4,
				CompletedRuns: 3,
				FailedRuns:    1,
				OtherRuns:     0,
				SuccessRate:   &successRate,
				AvgDurationMs: &averageDuration,
				MinDurationMs: &minDuration,
				MaxDurationMs: &maxDuration,
			}},
			Stages: []readservice.TelemetryStageStats{{
				Gaggle:               "core",
				Workflow:             "implementation",
				Stage:                "implement",
				TotalAttempts:        4,
				SucceededAttempts:    3,
				FailedAttempts:       1,
				SuccessRate:          &successRate,
				AvgDurationMs:        &averageDuration,
				MinDurationMs:        &minDuration,
				MaxDurationMs:        &maxDuration,
				DurationSamples:      4,
				P50DurationMs:        &minDuration,
				P95DurationMs:        &maxDuration,
				TokenSamples:         4,
				P50Tokens:            &p50Tokens,
				P95Tokens:            &p95Tokens,
				CostSamples:          4,
				P50CostUSD:           &p50CostUSD,
				P95CostUSD:           &p95CostUSD,
				RetryWasteAttempts:   1,
				RetryWasteDurationMs: &retryWasteDuration,
				RetryWasteTokens:     &retryWasteTokens,
				RetryWasteCostUSD:    &retryWasteCostUSD,
			}},
			Usage: []readservice.TelemetryUsageStats{{
				Scope:              "workflow",
				Gaggle:             "core",
				Workflow:           "implementation",
				TotalAttempts:      4,
				TokenSamples:       4,
				P50Tokens:          &p50Tokens,
				P95Tokens:          &p95Tokens,
				CostSamples:        4,
				P50CostUSD:         &p50CostUSD,
				P95CostUSD:         &p95CostUSD,
				RetryWasteAttempts: 1,
				RetryWasteTokens:   &retryWasteTokens,
				RetryWasteCostUSD:  &retryWasteCostUSD,
			}},
			Models: []readservice.TelemetryModelStats{{
				Model:                  "gpt-5.4",
				UsageSamples:           3,
				InputTokenSamples:      3,
				InputTokens:            &modelInputTokens,
				OutputTokenSamples:     3,
				OutputTokens:           &modelOutputTokens,
				PremiumRequestSamples:  3,
				CopilotPremiumRequests: &modelPremiumRequests,
				CostSamples:            3,
				CostUSD:                &modelCostUSD,
			}},
		},
		TelemetryErrorSignatures: readservice.TelemetryErrorSignaturesResult{
			Items: []readservice.TelemetryErrorSignature{{
				Code:           "stage_failed",
				ErrorClass:     "unknown",
				Count:          3,
				LastSeen:       timestamp,
				ExampleRunID:   "run-123",
				ExampleStage:   "implement",
				ExampleAttempt: 1,
			}},
		},
		TelemetryErrors: readservice.TelemetryErrorsPage{
			Items: []readservice.TelemetryError{{
				RunID:      "run-123",
				Workflow:   "implementation",
				Stage:      "implement",
				Attempt:    1,
				Code:       "stage_failed",
				ErrorClass: "workflow",
				Message:    "stage failed",
				OccurredAt: timestamp,
			}},
			NextCursor: "next-error",
		},
		EventInvalidation: Invalidation{
			Cursor: "fixture:9",
			Models: []string{"instance", "run", "workflow"},
			RunIDs: []string{"run-123"},
			Workflows: []WorkflowRef{{
				Gaggle: "core",
				Name:   "implementation",
			}},
		},
		ErrorEnvelope: ErrorEnvelope{
			Error: APIError{
				Code:    "not_found",
				Message: "requested resource was not found",
			},
		},
	}
}
