apiVersion: goobers.dev/v1alpha1
kind: Manifest
metadata:
  name: demo-instance
  annotations:
    goobers.dev/allow-preview-features: "true"
spec:
  instance:
    name: demo
    environment: dev
  gaggles:
    - demo
